Repository recodehive/machine-learning-repos, pull requests merged in 2024-07, with the labels that each got.

#520 ROC Curve
  ROC Curve/ROC_Curve_Report.docx
  ROC Curve/ROCcurve.ipynb
  ROC Curve/requirement.txt
Labels: gssoc, level1

#517 Added a new Data Imputation Technique
  Data Cleaning Techniques/GMM-imputer.ipynb
Labels: gssoc, level1

#433 eye disease detection
  Eye Diseases Detection/Images/Model Eval.png
  Eye Diseases Detection/Images/cataract.png
  Eye Diseases Detection/Images/countplot.png
  Eye Diseases Detection/Images/diabetic_retionpathy.png
  Eye Diseases Detection/Images/eye disease acc.png
  Eye Diseases Detection/Images/glucoma.png
  Eye Diseases Detection/Images/model.png
  Eye Diseases Detection/Images/normal.png
  Eye Diseases Detection/Images/true& predict eye disease.jpg
  Eye Diseases Detection/Model/Models/Eye_Diseases_Classification.ipynb
  Eye Diseases Detection/README.md
Labels: gssoc, level1

#522 Feature Added : Image Stitching
  Image Stitching/Dataset/Glacier/CIMG4017.JPG
  Image Stitching/Dataset/Glacier/CIMG4018.JPG
  Image Stitching/Dataset/Mountain/hill1.jpg
  Image Stitching/Dataset/Mountain/hill2.jpg
  Image Stitching/README.md
  Image Stitching/Result/Glacier/output1.jpg
  Image Stitching/Result/Glacier/output2.jpg
  Image Stitching/Result/Mountain/output1.jpg
  Image Stitching/Result/Mountain/output2.jpg
  Image Stitching/stitching.ipynb
Labels: gssoc, level1

#536 added new folder for Bitcoin price prediction
  Bitcoin-Price-Predictor/Bitc.csv
  Bitcoin-Price-Predictor/bitcoin-price-prediction.ipynb
  Bitcoin-Price-Predictor/readme.md
  Bitcoin-Price-Predictor/requirements.txt
Labels: gssoc, level1

#533 Added Resnet101
  ResNet101/ResNet101.ipynb
Labels: gssoc, level1

#500 added Dog Breed Classification using CNN
  Dog_Breed_Classification_CNN/Dog_Breed_classification.ipynb
  Dog_Breed_Classification_CNN/README.md
  Dog_Breed_Classification_CNN/app.py
  Dog_Breed_Classification_CNN/output/ROC_Curve_CNN.png
  Dog_Breed_Classification_CNN/output/bar_char-2.png
  Dog_Breed_Classification_CNN/output/bar_chart-1.png
  Dog_Breed_Classification_CNN/output/confusion_matrix_CNN.png
  Dog_Breed_Classification_CNN/output/img_class_analysis.png
  Dog_Breed_Classification_CNN/output/model_analysis.png
  Dog_Breed_Classification_CNN/output/predicted_class_CNN.png
  Dog_Breed_Classification_CNN/requirements.txt
  Dog_Breed_Classification_CNN/webapp.mp4
Labels: gssoc, level1

#425 Pre-Processing Techniques in DL
  Preprocessing Techniques of DL/Preprocessing Techniques.ipynb
Labels: gssoc, level1

#539 Stress Level Detection
  Stress Level Detection/StressLevelDetection.ipynb
  Stress Level Detection/requirement.txt
  Stress Level Detection/stress_data.csv
Labels: gssoc, level1

#545 readme file Airlines Delay Prediction under gssoc ##538
  Airlines Delay Prediction/README.md
Labels: gssoc, level1

#543 Update README.md gsoc issue #529
  README.md
Labels: gssoc, level1

#544 Update Readme.md gssoc issue #523
  Activation_and_Loss_function/Readme.md
Labels: gssoc, level1

#548 Analyze of titanic dataset #532 solved
  .ipynb_checkpoints/Analysis of Titanic_dataset-checkpoint.ipynb
  Analysis of Titanic_dataset.ipynb
  titanic_Data_Train1.csv
Labels: gssoc, level1

#547 Crop disease classification model
  Crop Disease Classification/README.md
  Crop Disease Classification/crop-disease-classification.ipynb
Labels: gssoc, level1

#558 Obesity prediction
  Obesity Predicition using XGBOOST.zip
  Obesity prediction using XGBOOST.ipynb
Labels: gssoc, level1

#560 Home Income prediction using Random forest ,GBM , XGBoost and Multiple linear regression
  Home_income_prediction_using_GBM/Home_income_prediction_notebook.ipynb
  Home_income_prediction_using_GBM/app.py
  Home_income_prediction_using_GBM/gb_model_income.pkl
  Home_income_prediction_using_GBM/home_income_dataset.csv
  Home_income_prediction_using_GBM/image/Bar_graph.png
  Home_income_prediction_using_GBM/image/actual_Vs_predicted_GBM.png
  Home_income_prediction_using_GBM/image/actual_Vs_predicted_SVM.png
  Home_income_prediction_using_GBM/image/actual_Vs_predicted_XGBoost.png
  Home_income_prediction_using_GBM/image/actual_Vs_predicted_multiple_linear_regression.png
  Home_income_prediction_using_GBM/image/box_plot_income_distribution.png
  Home_income_prediction_using_GBM/image/count_plot_age.png
  Home_income_prediction_using_GBM/image/pie_chart.png
  Home_income_prediction_using_GBM/image/scatter_plot.png
  Home_income_prediction_using_GBM/image/violin_plot_matplot.png
  Home_income_prediction_using_GBM/image/violin_plot_plotly.png
  Home_income_prediction_using_GBM/readme.md
  Home_income_prediction_using_GBM/requirements.txt
  Home_income_prediction_using_GBM/static/script.js
  Home_income_prediction_using_GBM/static/style.css
  Home_income_prediction_using_GBM/templates/index.html
  Home_income_prediction_using_GBM/webcam.mp4
Labels: gssoc, level1

#572 Mental disorder classification model
  Mental Disorder Classification/Dataset-Mental-Disorders.csv
  Mental Disorder Classification/mental-disorder-classification.ipynb
Labels: gssoc, level1

#569 Added Youtube_ad_view_prediction project
  Youtube-ad_view_prediction.ipynb
Labels: gssoc, level1

#568 Loan Status Prediction
  Loan Status Prediction/Project_6_Loan_Status_Prediction.ipynb
  Loan Status Prediction/train_u6lujuX_CVtuZ9i (1).csv
Labels: gssoc, level1

#561 Food Allergy Prediction (Deep Learning)
  Food Allergy Prediction/Food Allergy Prediction.ipynb
  Food Allergy Prediction/food allergy data.csv
  Food Allergy Prediction/requirement.txt
Labels: gssoc, level1

#577 Bird species classification model
  Bird species classification/bird-species-classification.ipynb
Labels: level1

#579 Added Lung Cancer Prediction using Machine Learning
  Lung Cancer Detection using ML/Lung_Cancer_Prediction.ipynb
  Lung Cancer Detection using ML/Lung_cancer.csv
  Lung Cancer Detection using ML/app.py
  Lung Cancer Detection using ML/gradient_boosting_model.pkl
  Lung Cancer Detection using ML/images/Box_plot_processed.png
  Lung Cancer Detection using ML/images/age_wise_smoking_status.png
  Lung Cancer Detection using ML/images/bar_plot.png
  Lung Cancer Detection using ML/images/box_plot.png
  Lung Cancer Detection using ML/images/box_plot_unporcessed.png
  Lung Cancer Detection using ML/images/correaltion_heatmap.png
  Lung Cancer Detection using ML/images/count_plot_plotly.png
  Lung Cancer Detection using ML/images/countpLot.png
  Lung Cancer Detection using ML/images/gbm_confusion_matrix.png
  Lung Cancer Detection using ML/images/naive_bayes_confusion_matrix.png
  Lung Cancer Detection using ML/images/pie_chart_lung_cancer.png
  Lung Cancer Detection using ML/images/rf_confusion_matrix.png
  Lung Cancer Detection using ML/images/sunburst_plot.png
  Lung Cancer Detection using ML/images/violin_plot.png
  Lung Cancer Detection using ML/images/xgboost_confusion_matrix.png
  Lung Cancer Detection using ML/readme.md
  Lung Cancer Detection using ML/requirements.txt
  Lung Cancer Detection using ML/webapp.mp4
Labels: gssoc, level1

#578 Covid Detection through x-ray Image #454 issue fixed
  XrayimageCovidDetection/CovidFromXrayImage.ipynb
  XrayimageCovidDetection/readme.md
  XrayimageCovidDetection/requirement.txt
Labels: gssoc, level1

#582 Titanic Survival Prediction Using ML issue #581
  TItanicSurvivalAnalysis/TitanicSurvivalAnalysis.ipynb
  TItanicSurvivalAnalysis/gender_submission.csv
  TItanicSurvivalAnalysis/readme.md
  TItanicSurvivalAnalysis/requirement.txt
  TItanicSurvivalAnalysis/test.csv
  TItanicSurvivalAnalysis/train.csv
  Youtube-Toxic-Comment-Classification/image/Power-In-Positivity.jpg
Labels: gssoc, level1

#470 Adding Data Analysis of Tech Stocks
  Data Analysis of Tech Stocks/Data_Analysis_of_Tech_Stocks.ipynb
  Data Analysis of Tech Stocks/README.md
  Data Analysis of Tech Stocks/big_tech_companies.csv
  Data Analysis of Tech Stocks/big_tech_stock_prices.csv
Labels: gssoc, level1

#528 Added Salary Prediction Model
  Salary Prediction Web App/SalaryPrediction.ipynb
  Salary Prediction Web App/__pycache__/explore_page.cpython-39.pyc
  Salary Prediction Web App/__pycache__/predict_page.cpython-39.pyc
  Salary Prediction Web App/app.py
  Salary Prediction Web App/explore_page.py
  Salary Prediction Web App/predict_page.py
  Salary Prediction Web App/readME.md
  Salary Prediction Web App/saved_steps.pkl
Labels: gssoc, level1

#527 #506 Added OkCupid Profiles Analysis
  OkCupid Profiles Analysis/Images/180602690-386b0428-37cd-497b-81f4-a367e4cdb4e5.png
  OkCupid Profiles Analysis/Images/180602692-314aa88d-9278-4319-a41f-3e1e1ac39836.png
  OkCupid Profiles Analysis/Images/180602696-899745fb-2491-4c11-915e-a8e420dd654f.png
  OkCupid Profiles Analysis/Images/180602700-ade00348-bb6c-451f-a3eb-7147e426490d.png
  OkCupid Profiles Analysis/Images/180602702-57984f25-1d14-4e56-b645-45312b7b61f7.png
  OkCupid Profiles Analysis/Images/180602706-7229335b-5ee2-4141-aa3b-a5e51c369a63.png
  OkCupid Profiles Analysis/Images/180602709-02224ebe-900e-43f4-b841-ab7852f77449.png
  OkCupid Profiles Analysis/Model/OkCupid Profiles Analysis .ipynb
  OkCupid Profiles Analysis/Model/README.md
  OkCupid Profiles Analysis/requirements.txt
Labels: gssoc, level1

#589 Add covid x-ray image classification
  Covid19 Xray Image Classification/Images/DenseNet121_predictions/0e775fe9-7a73-49cd-bf74-3fa33f76e2a5.png
  Covid19 Xray Image Classification/Images/DenseNet121_predictions/5ef690cb-9c3b-476b-8aeb-c63847941837.png
  Covid19 Xray Image Classification/Images/DenseNet121_predictions/7e024ac4-f3b4-4832-a776-0c2bb93b2c56.png
  Covid19 Xray Image Classification/Images/DenseNet121_predictions/8af20033-5829-4bdc-aeef-db9b5f63c387.png
  Covid19 Xray Image Classification/Images/InceptionV3_predictions/54a01ad5-ad98-4506-94a6-51cf178b3c4d.png
  Covid19 Xray Image Classification/Images/InceptionV3_predictions/55c53623-3f9b-4cf3-8624-7a509b7e7478.png
  Covid19 Xray Image Classification/Images/InceptionV3_predictions/8b73d11e-6df6-4332-9807-d0e37e2bb100.png
  Covid19 Xray Image Classification/Images/InceptionV3_predictions/9f819a75-9fca-4a51-99ac-097194a7d43e.png
  Covid19 Xray Image Classification/Images/MobieNetV2_predictions/4d8f7d2a-3ef1-4942-820b-3055bb4dc16f.png
  Covid19 Xray Image Classification/Images/MobieNetV2_predictions/6bbe9b43-1bc7-47e1-9aaa-69b4fa8ef1c6.png
  Covid19 Xray Image Classification/Images/MobieNetV2_predictions/92336470-2301-4a96-9a6e-fba21558bff6.png
  Covid19 Xray Image Classification/Images/MobieNetV2_predictions/feaf9857-f711-41b8-8086-343dc8610c46.png
  Covid19 Xray Image Classification/Images/VGG16_predictions/04701e86-c359-4103-899a-55faa0e6ea08.png
  Covid19 Xray Image Classification/Images/VGG16_predictions/4baaf1a6-0eed-4833-bf01-21628c39cf0e.png
  Covid19 Xray Image Classification/Images/VGG16_predictions/4e652e15-23c6-4317-861f-9bd5d14a5940.png
  Covid19 Xray Image Classification/Images/VGG16_predictions/af7f9523-cc21-454a-8f1c-35facfb2a89e.png
  Covid19 Xray Image Classification/Images/Xception_predictions/61a8aed3-bd82-4ff9-8ab9-5dd37a41d889.png
  Covid19 Xray Image Classification/Images/Xception_predictions/86bf04a4-43cc-4741-b300-8ad978c46132.png
  Covid19 Xray Image Classification/Images/Xception_predictions/89435ec5-a3b2-4942-a735-3ec28f9a918c.png
  Covid19 Xray Image Classification/Images/Xception_predictions/fb82b37b-d970-48cc-a159-8e9587f35f1a.png
  Covid19 Xray Image Classification/Images/bar_chart.png
  Covid19 Xray Image Classification/Images/image_path_distribution.png
  Covid19 Xray Image Classification/Images/pie.png
  Covid19 Xray Image Classification/Models/README.md
  Covid19 Xray Image Classification/Models/models_COVID_19.ipynb
  Covid19 Xray Image Classification/requirement.txt
Labels: gssoc, level1

#606 Coordinate Reference Systems (CRS) #564
  Coordinate Reference Systems (CRS)/UCoordinate_Reference_Systems_(CRS)_.ipynb
  Coordinate Reference Systems (CRS)/coordinate_reference_systems.docx
  Coordinate Reference Systems (CRS)/requirement.txt
Labels: gssoc, level1

#603 Reading and Writing Geospatial Data
  Reading and Writing Geospatial Data/Reading_and_Writing_Geospatial_Data_.ipynb
  Reading and Writing Geospatial Data/geospatial_data_operations.docx
  Reading and Writing Geospatial Data/requirement.txt
  Reading and Writing Geospatial Data/selected_countries.geojson
Labels: gssoc, level1

#599 Added Student Student Dropout Rates Prediction
  Predicting Student Dropout Rates/Dataset/Reframed_Student_Dropout_rate.csv
  Predicting Student Dropout Rates/Model/Student_Dropout_Rates_Prediction_using_Logistic_Regression,_K_Nearest_Neighbors_(KNN)_and_K_Means_Clustering.ipynb
  Predicting Student Dropout Rates/requirements.txt
Labels: gssoc, level1

#597 Harry Potter Data ANalysis (EDA) using ML
  HarryPotter/Characters.csv
  HarryPotter/HarryPotterDataAnalysis(EDA)_.ipynb
  HarryPotter/Movies.csv
  HarryPotter/Spells.csv
  HarryPotter/readme.md
  HarryPotter/requirement.txt
  HarryPotter/wordCloud.png
Labels: gssoc, level1

#595 Creating a Rock mine classification ML model and solving issue #524
  Rock Mine Prediction using SONAR/README.md
  Rock Mine Prediction using SONAR/requirements.txt
  Rock Mine Prediction using SONAR/rock_mine_detection.ipynb
  Rock Mine Prediction using SONAR/sonar_data.csv
Labels: gssoc, level1

#594 Chest X-ray - Tuberculosis Disease Prediction
  Chest X-ray - Tuberculosis Disease Prediction/Dataset/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/07d23d26-602e-45b3-89a9-adc19a24a93b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/73a27086-f976-43d2-bbc3-34d1148e2cdd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/83be1e95-d591-41cb-b6a5-330af1de15c1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/941fe4f5-8176-4fc0-b2e5-1cc41e58138f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/01209f9f-e709-4a7a-a14b-97f98cdb16a6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/a970945f-aedf-4ac7-a4ee-e3f01fedcbb4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b12522d2-e7f9-43bb-b9ec-0d862dfb3a2b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b6627c83-2b71-411e-8a3b-ecb8a93b35f9.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/495e63b4-00da-42c1-9f88-21f74bcd083a.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/79b66dc3-b8f7-42fb-b782-4764d3bcbf54.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cd214e19-6e33-4a6d-9d40-51a6fc182425.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cef531b0-8c62-474d-8432-3b28d31586dd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/09672514-0d74-4ba3-b83f-34b7dce90ce6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/66b55d5b-c0dc-4c22-9c9d-574ad61aab1e.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/7df6144a-37f3-47d5-b42b-39a6d0e83ff4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/c9365032-e058-4e78-93f9-e9654992bbf1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/369f577f-fde9-48eb-a4ad-d9ee64a8f903.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/3c63b249-af3e-4732-8109-7595c30b09ec.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/bef2f489-15d6-4f72-a33e-5c306d33833f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/cd93c4f3-2055-4daf-919a-9d88bf1d18ca.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/bar_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/image_path_distribution.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/pie_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Models/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Models/models_Chest_X_ray_Tuberculosis_Disease_Prediction(1).ipynb
  Chest X-ray - Tuberculosis Disease Prediction/requirement.txt
Labels: gssoc, level1

#616 Gold Price Prediction
  gold price prediction/Project_6_Gold_Price_Prediction.ipynb
  gold price prediction/gld_price_data.csv
Labels: gssoc, level1

#615 DNA Classification
  DNA-Classification-Machine-Learning-Project-master/DNA-Classification-Machine-Learning-Project-master/DNA Classification Code.ipynb
  DNA-Classification-Machine-Learning-Project-master/DNA-Classification-Machine-Learning-Project-master/README.md
  DNA-Classification-Machine-Learning-Project-master/DNA-Classification-Machine-Learning-Project-master/promoters.data
Labels: gssoc, level1

#641 Stroke Prediction
  Stroke Prediction/Dataset/healthcare-dataset-stroke-data.csv
  Stroke Prediction/Model/README.md
  Stroke Prediction/Model/StrokePrediction-EDA.ipynb
Labels: gssoc, level1

#639 Mushroom classification model
  Mushroom Classification Model/Mushroom Classification Model.ipynb
  Mushroom Classification Model/README.md
Labels: gssoc, level1

#635 Added Alzheimer's Disease Prediction
  Alzheimer's Disease Prediction/Dataset/README.md
  Alzheimer's Disease Prediction/Images/26 (19).jpg
  Alzheimer's Disease Prediction/Images/26 (20).jpg
  Alzheimer's Disease Prediction/Images/26 (21).jpg
  Alzheimer's Disease Prediction/Images/26 (22).jpg
  Alzheimer's Disease Prediction/Images/26 (23).jpg
  Alzheimer's Disease Prediction/Images/26 (24).jpg
  Alzheimer's Disease Prediction/Images/26 (25).jpg
  Alzheimer's Disease Prediction/Images/26 (62).jpg
  Alzheimer's Disease Prediction/Images/26 (63).jpg
  Alzheimer's Disease Prediction/Images/26 (64).jpg
  Alzheimer's Disease Prediction/Images/26 (65).jpg
  Alzheimer's Disease Prediction/Images/26 (66).jpg
  Alzheimer's Disease Prediction/Images/image.jpg
  Alzheimer's Disease Prediction/Models/alzheimer-detection.ipynb
  Alzheimer's Disease Prediction/Requirements.txt
  Alzheimer's Disease Prediction/Web-App/Screenshot 2024-05-14 081538.png
  Alzheimer's Disease Prediction/Web-App/app.py
  Alzheimer's Disease Prediction/Web-App/demo (1).mp4
  Alzheimer's Disease Prediction/Web-App/demo-1.mp4
  Alzheimer's Disease Prediction/Web-App/readme.md
  Alzheimer's Disease Prediction/Web-App/thumbnail.png
  Alzheimer's Disease Prediction/Web-App/thumbnaill.png
Labels: gssoc, level1

#634 Using ANN, analysing and predicting customer purchase behaviour.
  Customer-Purchase_Behaviour-UsingANN/Customer Purchase Behaviour using ANN.ipynb
  Customer-Purchase_Behaviour-UsingANN/customer_purchase_data.csv
Labels: gssoc, level1

#662 Added Online Courses Usage and History Dataset
  Online Courses Usage by ML Models/Dataset/online_courses_uses.csv
  Online Courses Usage by ML Models/Images/Comparision of Platforms.png
  Online Courses Usage by ML Models/Images/K Means Clusters.png
  Online Courses Usage by ML Models/Images/LSTM.png
  Online Courses Usage by ML Models/Images/Trends in Online Learning.png
  Online Courses Usage by ML Models/Model/Online_Courses_Usage_and_Historical_Dataset_Using_Machine_Learning_Models.ipynb
  Online Courses Usage by ML Models/requirements.txt
Labels: gssoc, level1

#661 Machine Failure Prediction
  Machine Failure Prediction Using Sensor Data/Dataset/Readme.md
  Machine Failure Prediction Using Sensor Data/Readme.md
  Machine Failure Prediction Using Sensor Data/machine_failure_prediction_using_sensor_data.ipynb
Labels: gssoc, level1

#660 Grade prediction
  Grade_Prediction/README.md
  Grade_Prediction/grade_prediction.ipynb
  Grade_Prediction/grades.csv
Labels: gssoc, level1

#658 Visualizing geospatial data with Matplotlib and Geopandas
  Visualizing geospatial data with Matplotlib and Geopandas/Visualizing_geospatial_data_with_Matplotlib_and_Geopandas.ipynb
  Visualizing geospatial data with Matplotlib and Geopandas/requirement.txt
  Visualizing geospatial data with Matplotlib and Geopandas/synthetic_geospatial_data.csv
Labels: gssoc, level1

#656 Flood Prediction
  Flood Prediction.zip
Labels: gssoc, level1

#654 SecureTransact: Advanced Fraud Detection for Financial Transactions
  Advanced Fraud Detection for Financial Transactions/AccredianFile.ipynb
  Advanced Fraud Detection for Financial Transactions/Data Dictionary.txt
  Advanced Fraud Detection for Financial Transactions/accuracy SC.png
  Advanced Fraud Detection for Financial Transactions/model.ipynb
  Advanced Fraud Detection for Financial Transactions/readme.md
Labels: gssoc, level1

#646 Added Infant Health Prediction
  Infant Health Prediction/Dataset/Synthetic-Infant-Health-Data.csv
  Infant Health Prediction/Infant_health_predictions_EDA.ipynb
  Infant Health Prediction/README.md
Labels: gssoc, level1

#667 Face Recognition for Attendance Management System #652 issued closed
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/.gitignore
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/.name
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/Face Recognition for Attendance Management System.iml
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/inspectionProfiles/Project_Default.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/inspectionProfiles/profiles_settings.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/misc.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/.idea/modules.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/.gitignore
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/ML6-SAn.iml
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/inspectionProfiles/profiles_settings.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/misc.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/modules.xml
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/Attendance.csv
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/AttendenceProject.py
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/GUI.py
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/dlib-19.24.1-cp311-cp311-win_amd64.whl
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/gui2.py
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/bg.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/bill_gates.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/elonmuk1.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/elonmusk2.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/bill_gates.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/elonmuk1.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/mark1.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/will_ferral.jpg
  Face_Recognition_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/program.py
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/.gitignore
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/.name
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/Face Recognition for Attendance Management System.iml
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/inspectionProfiles/Project_Default.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/inspectionProfiles/profiles_settings.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/misc.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/.idea/modules.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/.gitignore
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/ML6-SAn.iml
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/inspectionProfiles/profiles_settings.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/misc.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/.idea/modules.xml
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/Attendance.csv
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/AttendenceProject.py
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/GUI.py
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/dlib-19.24.1-cp311-cp311-win_amd64.whl
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/gui2.py
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/bg.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/bill_gates.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/elonmuk1.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagebasic/elonmusk2.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/bill_gates.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/elonmuk1.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/mark1.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/imagesatted/will_ferral.jpg
  Face_Recongiton_For_Attendance_Management_System/ML Project/ML_Project/ML6-SAn/program.py
Labels: gssoc, level1

#664 Anemia disease detection using Machine learning
  anaemia_disease_detection_using_ML/Dataset/anaemia_disease_detection.csv
  anaemia_disease_detection_using_ML/Images/anaemic-vs-gender.png
  anaemia_disease_detection_using_ML/Images/box_plot.png
  anaemia_disease_detection_using_ML/Images/box_plot_processed.png
  anaemia_disease_detection_using_ML/Images/cf_gbm.png
  anaemia_disease_detection_using_ML/Images/cf_naive_bayes.png
  anaemia_disease_detection_using_ML/Images/cf_rf.png
  anaemia_disease_detection_using_ML/Images/cf_svm.png
  anaemia_disease_detection_using_ML/Images/correlation_test.png
  anaemia_disease_detection_using_ML/Images/gender_distribution.png
  anaemia_disease_detection_using_ML/Images/histogram.png
  anaemia_disease_detection_using_ML/Images/model_comparison.png
  anaemia_disease_detection_using_ML/Images/pie_chart_anaemia.png
  anaemia_disease_detection_using_ML/Images/roc_curve.png
  anaemia_disease_detection_using_ML/Images/scatter-1.png
  anaemia_disease_detection_using_ML/Images/scatter-2.png
  anaemia_disease_detection_using_ML/Images/scatter-3.png
  anaemia_disease_detection_using_ML/Images/violin_plot.png
  anaemia_disease_detection_using_ML/Webapp/anaemia_webapp.mp4
  anaemia_disease_detection_using_ML/Webapp/app.py
  anaemia_disease_detection_using_ML/model/anaemia_disease_detection.ipynb
  anaemia_disease_detection_using_ML/model/model_rf.joblib
  anaemia_disease_detection_using_ML/readme.md
  anaemia_disease_detection_using_ML/requirements.txt
Labels: gssoc, level1

#644 Added Health insurance price prediction using Machine learning
  Health Insurance Price prediction/Health_insurance_cost_prediction.ipynb
  Health Insurance Price prediction/Images/boxplot-1.png
  Health Insurance Price prediction/Images/boxplot-2_processed.png
  Health Insurance Price prediction/Images/correlation_matrix.png
  Health Insurance Price prediction/Images/countplot.png
  Health Insurance Price prediction/Images/cross_validation_graph.png
  Health Insurance Price prediction/Images/evaluation_metrix_comparison_all_models.png
  Health Insurance Price prediction/Images/gbm_actual_vs_predicted.png
  Health Insurance Price prediction/Images/histogram.png
  Health Insurance Price prediction/Images/mlr_actual_vs_predicted.png
  Health Insurance Price prediction/Images/pie-chart-1.png
  Health Insurance Price prediction/Images/pie-chart-2.png
  Health Insurance Price prediction/Images/rf_actual_vs_predicted.png
  Health Insurance Price prediction/Images/scatterplot.png
  Health Insurance Price prediction/Images/violin-plot.png
  Health Insurance Price prediction/Images/xgboost_actual_Vs_predicted.png
  Health Insurance Price prediction/app.py
  Health Insurance Price prediction/label_encoders.pkl
  Health Insurance Price prediction/linear_regression_model.pkl
  Health Insurance Price prediction/readme.md
  Health Insurance Price prediction/requirements.txt
  Health Insurance Price prediction/webapp.mp4
Labels: gssoc, level1

#683 Endometrial Cancer Prediction
  Endometrial Cancer Prediction/Endometrial Cancer Prediction Dataset.ipynb
  Endometrial Cancer Prediction/README.md
  Endometrial Cancer Prediction/Uterine Corpus Endometrial Carcinoma dataset.csv
Labels: gssoc, level1

#682 Added DenseNet121 model
  DenseNet121/DenseNet121.ipynb
Labels: gssoc, level1

#678 Big Mart Sales Prediction
  Big Mart Sales Prediction/Project_12_Big_Mart_Sales_Prediction.ipynb
  Big Mart Sales Prediction/Test.csv
  Big Mart Sales Prediction/Train.csv
Labels: gssoc, level1

#687 Added Anemia Predictions
  Anemia Prediction/Anemia_prediction.ipynb
  Anemia Prediction/Readme.md
  Anemia Prediction/anemia_dataset.csv
Labels: gssoc, level1

#697 Patient Survival Prediction
  patientSurvivalPrediction/PatientSurvival.ipynb
  patientSurvivalPrediction/app.py
  patientSurvivalPrediction/haberman.csv
  patientSurvivalPrediction/index.html
  sentenceAutoCompletion/SentenceAutoCompletion.ipynb
  sentenceAutoCompletion/readme.md
  sentenceAutoCompletion/requirement.txt
Labels: gssoc, level1

#694 Nifty Fifty Data ANalysis
  nifty50DataAnalysis/Nifty50DataAnalysis.ipynb
  nifty50DataAnalysis/readme.md
  nifty50DataAnalysis/requirement.txt
Labels: gssoc, level1

#692 Glass Bangle Defects Detection
  Glass Bangle Defects Detection/Datasets/README.md
  Glass Bangle Defects Detection/Images/CNN model.png
  Glass Bangle Defects Detection/Images/CNN-Keras-Attention.png
  Glass Bangle Defects Detection/Images/CNN-Keras.png
  Glass Bangle Defects Detection/Images/CNN-architecture-based-on-GoogLeNet-model.ppm.png
  Glass Bangle Defects Detection/Images/GoogleNet-Validation.png
  Glass Bangle Defects Detection/Images/GoogleNet-train.png
  Glass Bangle Defects Detection/Images/ResNet-Validation.png
  Glass Bangle Defects Detection/Images/ResNet-training.png
  Glass Bangle Defects Detection/Images/Residual-Block.PNG
  Glass Bangle Defects Detection/Model/Custom-Model.ipynb
  Glass Bangle Defects Detection/Model/Glass-Bangle-Defect-Detection.ipynb
  Glass Bangle Defects Detection/README.md
  Glass Bangle Defects Detection/requirements.txt
Labels: gssoc, level1

#689 Decision Tree Visualizer tool
  DecisionTreeVisualiser-main/.gitignore
  DecisionTreeVisualiser-main/Procfile
  DecisionTreeVisualiser-main/README.md
  DecisionTreeVisualiser-main/app.py
  DecisionTreeVisualiser-main/requirements.txt
  DecisionTreeVisualiser-main/setup.sh
Labels: gssoc, level1

#688 Added Employee Attrition data Prediction
  Employee Attrition data/Dataset/employee_attrition_data.csv
  Employee Attrition data/Images/Correlation Heatmap.png
  Employee Attrition data/Images/Employee Data Attrition.png
  Employee Attrition data/Images/LSTM Graph.png
  Employee Attrition data/Model/Employee_Attrition_data_Prediction.ipynb
  Employee Attrition data/requirements.txt
Labels: gssoc, level1

#645 Facial Emotion Detection
  Facial Emotion Detection/Dataset/Readme.md
  Facial Emotion Detection/Images/00_baseline_cnn/00_data_samples.png
  Facial Emotion Detection/Images/00_baseline_cnn/01_model_summary.png
  Facial Emotion Detection/Images/00_baseline_cnn/02_training_curves.png
  Facial Emotion Detection/Images/00_baseline_cnn/03_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/00_config1_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/01_config1_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/02_config2_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/03_config2_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/04_config3_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/05_config3_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/00_noaug_featext_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/01_noaug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/02_noaug_finetune_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/03_noaug_finetune_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/04_aug_featext_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/05_aug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/06_aug_finetune_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/07_aug_finetune_confusion_matrix.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/00_noaug_featext_training_curves (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/01_noaug_featext_confusion_matrix (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/02_noaug_finetune_training_curves (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/03_noaug_finetune_confusion_matrix (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/04_aug_featext_training_curves (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/05_aug_featext_confusion_matrix (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/06_aug_finetune_training_curves (1).png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/07_aug_finetune_confusion_matrix (1).png
  Facial Emotion Detection/Models/00_baseline_cnn.ipynb
  Facial Emotion Detection/Models/01_data_augmentation_cnn.ipynb
  Facial Emotion Detection/Models/02_transfer_learning_mobilenetv2.ipynb
  Facial Emotion Detection/Models/03_transfer_learning_efficientnetv2.ipynb
  Facial Emotion Detection/Models/README.md
  Facial Emotion Detection/Models/requirements.txt
  Facial Emotion Detection/README.md
Labels: gssoc, level1

#700 Brain Tumor Detection
  Brain Tumor Detection/Dataset/README.md
  Brain Tumor Detection/Images/README.md
  Brain Tumor Detection/Images/image-1.png
  Brain Tumor Detection/Images/image-10.png
  Brain Tumor Detection/Images/image-11.png
  Brain Tumor Detection/Images/image-2.png
  Brain Tumor Detection/Images/image-3.png
  Brain Tumor Detection/Images/image-4.png
  Brain Tumor Detection/Images/image-5.png
  Brain Tumor Detection/Images/image-6.png
  Brain Tumor Detection/Images/image-7.png
  Brain Tumor Detection/Images/image-8.png
  Brain Tumor Detection/Images/image-9.png
  Brain Tumor Detection/Images/image.png
  Brain Tumor Detection/Images/image12.png
  Brain Tumor Detection/Model/README.md
  Brain Tumor Detection/Model/brain_tumor_model.ipynb
  Brain Tumor Detection/README.md
  Brain Tumor Detection/Web App/Final.mp4
  Brain Tumor Detection/Web App/README.md
  Brain Tumor Detection/Web App/Screenshot 2024-05-13 221628.png
  Brain Tumor Detection/Web App/app.py
  Brain Tumor Detection/Web App/requirements.txt
  Brain Tumor Detection/Web App/styles/styles.css
  Brain Tumor Detection/Web App/styles/styles1.css
  Brain Tumor Detection/Web App/templates/error.html
  Brain Tumor Detection/Web App/templates/index.html
  Brain Tumor Detection/Web App/templates/result.html
  Brain Tumor Detection/requirements.txt
Labels: gssoc, level1

#708 Added Car Mileage Prediction
  Car Mileage Prediction/car-mlg-pred.csv
  Car Mileage Prediction/car_mileage_prediction.ipynb
Labels: gssoc, level1

#707 Added Google Recaptcha Image Classification
  Google Recaptcha Image Classification/Dataset/Readme.md
  Google Recaptcha Image Classification/Images/HyperparameterTestModel.png
  Google Recaptcha Image Classification/Images/bicycle.png
  Google Recaptcha Image Classification/Images/bridge.png
  Google Recaptcha Image Classification/Images/bus.png
  Google Recaptcha Image Classification/Images/car.png
  Google Recaptcha Image Classification/Images/chimney.png
  Google Recaptcha Image Classification/Images/crosswalk.png
  Google Recaptcha Image Classification/Images/hydrant.png
  Google Recaptcha Image Classification/Images/hyperparameterTestingTrainAccuracy.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingTrainLoss.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingValidationAccuracy.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingValidationLoss.svg
  Google Recaptcha Image Classification/Images/motorcycle.png
  Google Recaptcha Image Classification/Images/other.png
  Google Recaptcha Image Classification/Images/palm.png
  Google Recaptcha Image Classification/Images/stairs.png
  Google Recaptcha Image Classification/Images/trafficlight.png
  Google Recaptcha Image Classification/Model/GoogleRecaptcha.ipynb
  Google Recaptcha Image Classification/README.md
  Google Recaptcha Image Classification/requirement.txt
Labels: gssoc, level1

#705 Added Bitcoin Price Prediction
  Bitcoin Price Prediction/README.md
  Bitcoin Price Prediction/app.py
  Bitcoin Price Prediction/coin_Bitcoin.csv
  Bitcoin Price Prediction/price.png
  Bitcoin Price Prediction/requirements (1).txt
Labels: gssoc, level1

#666 added flight price prediction using machine learning
  flight price prediction/dataset/flight_dataset.csv
  flight price prediction/images/correlation_matrix.png
  flight price prediction/images/count_plot1.png
  flight price prediction/images/count_plot2.png
  flight price prediction/images/gbm.png
  flight price prediction/images/histogram1.png
  flight price prediction/images/histogram2.png
  flight price prediction/images/linear_regression.png
  flight price prediction/images/model_cmp_1.png
  flight price prediction/images/model_cmp_2.png
  flight price prediction/images/model_cmp_3.png
  flight price prediction/images/model_cmp_4.png
  flight price prediction/images/random_forest.png
  flight price prediction/images/scatter_plot.png
  flight price prediction/images/xgboost.png
  flight price prediction/model/flight_price_prediction.ipynb
  flight price prediction/readme.md
Labels: gssoc, level1

#677 added cataract eye disease classification using deep learning
  cataract_detection_vgg16/cataract_classification.ipynb
  cataract_detection_vgg16/images/accuracy_vs_epochs.png
  cataract_detection_vgg16/images/model_architecture.png
  cataract_detection_vgg16/images/normal_image.png
  cataract_detection_vgg16/images/prediction.png
  cataract_detection_vgg16/readme.md
Labels: gssoc, level1

#672 added diamond price prediction using machine learning
  Diamond_price_prediction_using_random_forest/diamond_price_prediction.ipynb
  Diamond_price_prediction_using_random_forest/diamonds.csv
  Diamond_price_prediction_using_random_forest/images/actual_vs__predicted_dt.png
  Diamond_price_prediction_using_random_forest/images/actual_vs_predicted_rf.png
  Diamond_price_prediction_using_random_forest/images/actual_vs_predicted_svm.png
  Diamond_price_prediction_using_random_forest/images/actual_vs_preidcted_lr.png
  Diamond_price_prediction_using_random_forest/images/box_plot-1.png
  Diamond_price_prediction_using_random_forest/images/box_plot-2.png
  Diamond_price_prediction_using_random_forest/images/box_plot.png
  Diamond_price_prediction_using_random_forest/images/correlation_matrix.png
  Diamond_price_prediction_using_random_forest/images/count-plot.png
  Diamond_price_prediction_using_random_forest/images/count_plot_2.png
  Diamond_price_prediction_using_random_forest/images/cross_validation.png
  Diamond_price_prediction_using_random_forest/images/histogram-1.png
  Diamond_price_prediction_using_random_forest/images/model_cmp.png
  Diamond_price_prediction_using_random_forest/images/pie_chart.png
  Diamond_price_prediction_using_random_forest/images/scatter-plot-1.png
  Diamond_price_prediction_using_random_forest/images/scatter_plot.png
  Diamond_price_prediction_using_random_forest/readme.md
Labels: gssoc, level1

#722 Herb prediction
  Herb-prediction/Main.ipynb
  Herb-prediction/readme.md
Labels: gssoc, level1

#721 Added Coffee Sales Prediction
  Coffee Sales Prediction/Dataset/index.csv
  Coffee Sales Prediction/Model/Coffee_Sales.ipynb
  Coffee Sales Prediction/requirements.txt
Labels: gssoc, level1

#713 Exchange Traded Funds
  Exchange Traded Funds/ETFs.csv
  Exchange Traded Funds/ETFs.ipynb
Labels: gssoc, level1

#712 Bitcoin Price Predictor Added
  Bitcoin Price Predictor/BTC-USD.csv
  Bitcoin Price Predictor/Bitcoin_Price_Prediction.ipynb
  Bitcoin Price Predictor/Final-Graph.png
  Bitcoin Price Predictor/README.md
Labels: gssoc, level1

#711 Added Dynamic Hedging Strategies
  Dynamic Hedging Strategies/Dynamic_Hedging_StrategiesReinforcementLear.ipynb
  Dynamic Hedging Strategies/dqn_agent.h5
  Dynamic Hedging Strategies/readme.md
  Dynamic Hedging Strategies/requirement.txt
  patientSurvivalPrediction/haberman.csv
Labels: gssoc, level1

#709 Detecting IoT Sensor Fault detection Using ML
  Detecting-IoT-Sensor-fault-using-ML/.gitignore
  Detecting-IoT-Sensor-fault-using-ML/README.md
  Detecting-IoT-Sensor-fault-using-ML/flowcharts/Artifact Data Ingestion Folder Structure.png
  Detecting-IoT-Sensor-fault-using-ML/flowcharts/HIGH LEVEL CODE FLOW.png
  Detecting-IoT-Sensor-fault-using-ML/main.py
  Detecting-IoT-Sensor-fault-using-ML/notebook/Classification using XGBoost.ipynb
  Detecting-IoT-Sensor-fault-using-ML/notebook/catboost_info/catboost_training.json
  Detecting-IoT-Sensor-fault-using-ML/notebook/catboost_info/learn/events.out.tfevents
  Detecting-IoT-Sensor-fault-using-ML/notebook/catboost_info/learn_error.tsv
  Detecting-IoT-Sensor-fault-using-ML/notebook/catboost_info/time_left.tsv
  Detecting-IoT-Sensor-fault-using-ML/notebook/catboost_info/tmp/cat_feature_index.8eabcf5a-dfab063a-6de8a9d3-527a7ef9.tmp
  Detecting-IoT-Sensor-fault-using-ML/requirements.txt
  Detecting-IoT-Sensor-fault-using-ML/saved_models/1676058009/model.pkl
  Detecting-IoT-Sensor-fault-using-ML/setup.py
Labels: gssoc, level1

#733 Crude-oil-forecasting
  Crude-oil-forecasting/crudeoil.ipynb
  Crude-oil-forecasting/dataset.csv
  Crude-oil-forecasting/readme.md
Labels: gssoc, level1

#731 Company Bankruptcy Using unsupervised added
  Company Bankruptcy Using unsupervised/Bank Customer Segmentation using K means,DBCAN.ipynb
  Company Bankruptcy Using unsupervised/readme.md
  Company Bankruptcy Using unsupervised/requirement.txt
  Company Bankruptcy Using unsupervised/result.png
  Company Bankruptcy Using unsupervised/result1.png
Labels: gssoc, level1

#741 Added Post Traumatic Stress Prediction
  Post Traumatic Stress Prediction/Dataset/readme.md
  Post Traumatic Stress Prediction/Models/main.py
  Post Traumatic Stress Prediction/Models/train.py
  Post Traumatic Stress Prediction/README.md
  Post Traumatic Stress Prediction/requirements.txt
Labels: gssoc, level1

#744 Sarcasm Detection For Cross Domain Applications #691 issue closed
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/.gitignore
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/Sarcasm-detection-in-cross-domain-applications-master.iml
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/inspectionProfiles/Project_Default.xml
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/inspectionProfiles/profiles_settings.xml
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/misc.xml
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/.idea/modules.xml
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/CNN_glove
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/bilstm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/cnn+lstm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/cnn_bilstm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/cnn_svm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/lstm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/lstm_svm_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/GloVe/sequential_glove.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/ML_Models.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/README.md
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/Sequential_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/bilstm+cnn_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/bilstm_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/cnn+lstm_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/cnn+svm_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/cnn_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/lstm+svm_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/Word2Vec/lstm_word2vec.py
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/finalAmazonDataset.xlsx
  Sarcasm_Detection_For_Cross_Domain_Applications/Sarcasm-detection-in-cross-domain-applications-master/Sarcasm-detection-in-cross-domain-applications-master/functions.py
Labels: gssoc, level1

#745 Added MNIST Digit Classification
  MNIST Digit Classification/Dataset/Readme.md
  MNIST Digit Classification/Images/bar graph.png
  MNIST Digit Classification/Images/confusion matrix.png
  MNIST Digit Classification/Images/histogram.png
  MNIST Digit Classification/Images/input visualisation.png
  MNIST Digit Classification/Images/pie chart.png
  MNIST Digit Classification/Images/training loss.png
  MNIST Digit Classification/Model/ANN_Handwritten_Digit_Classification.ipynb
  MNIST Digit Classification/Model/CNN_handwritten_digit_recogniser.ipynb
  MNIST Digit Classification/README.md
  MNIST Digit Classification/requirement.txt
Labels: gssoc, level1

#740 Drone Detection using YOLO
  Drone Detection Using YOLO/Datasets/README.md
  Drone Detection Using YOLO/Images/YOLO-structure-and-examples-of-multiclass-object-detection.png
  Drone Detection Using YOLO/Images/results_5m.png
  Drone Detection Using YOLO/Images/train_batch0.jpg
  Drone Detection Using YOLO/Images/val_batch0_pred.jpg
  Drone Detection Using YOLO/Model/Drone-Detection.ipynb
  Drone Detection Using YOLO/README.md
  Drone Detection Using YOLO/requirements.txt
  Drone Detection Using YOLO/runs/train/yolov5m_results/F1_curve.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/PR_curve.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/P_curve.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/R_curve.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/confusion_matrix.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/events.out.tfevents.1664457544.6f86aca8911c.1008.0
  Drone Detection Using YOLO/runs/train/yolov5m_results/hyp.yaml
  Drone Detection Using YOLO/runs/train/yolov5m_results/labels.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/labels_correlogram.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/opt.yaml
  Drone Detection Using YOLO/runs/train/yolov5m_results/results.csv
  Drone Detection Using YOLO/runs/train/yolov5m_results/results.png
  Drone Detection Using YOLO/runs/train/yolov5m_results/train_batch0.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/train_batch1.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/train_batch2.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch0_labels.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch0_pred.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch1_labels.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch1_pred.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch2_labels.jpg
  Drone Detection Using YOLO/runs/train/yolov5m_results/val_batch2_pred.jpg
Labels: gssoc, level1

#749 Flight_delay_prediction_project added
  Flight_delay_prediction_project/README.md
  Flight_delay_prediction_project/flight_delay.ipynb
Labels: gssoc, level1

#754 Thyroid Cancer Recurrence Prediction
  Thyroid Cancer Recurrence Prediction/Dataset/README.md
  Thyroid Cancer Recurrence Prediction/Dataset/Thyroid_Disease_Data.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_data.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_test.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_train.csv
  Thyroid Cancer Recurrence Prediction/Images/Adenopathy_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/Age_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/Age_Distribution_by_Smoking_Status.png
  Thyroid Cancer Recurrence Prediction/Images/Correlation_Matrix.png
  Thyroid Cancer Recurrence Prediction/Images/Gender_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/MLP_Model_Accuracy.png
  Thyroid Cancer Recurrence Prediction/Images/MosaicPlot.png
  Thyroid Cancer Recurrence Prediction/Images/Thyroid_Cancer_Recurrence_Dataset_EDA.png
  Thyroid Cancer Recurrence Prediction/Model/Profile_Report.html
  Thyroid Cancer Recurrence Prediction/Model/Thyroid_Cancer_Recurrence_Dataset_EDA.ipynb
  Thyroid Cancer Recurrence Prediction/Model/Thyroid_Cancer_Recurrence_Prediction_w_DL.ipynb
  Thyroid Cancer Recurrence Prediction/Model/autogluon_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/autogluon_model.pkl
  Thyroid Cancer Recurrence Prediction/Model/mlp_model.h5
  Thyroid Cancer Recurrence Prediction/Model/mlp_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model.pt
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model_params.json
  Thyroid Cancer Recurrence Prediction/README.md
  Thyroid Cancer Recurrence Prediction/requirements.txt
Labels: gssoc, level3

#752 Suicide and Depression Detection
  Sucide & Depression Detection/Dataset/README.md
  Sucide & Depression Detection/Images/GRU_Accuracy_Plot.png
  Sucide & Depression Detection/Images/Model_LSTMs_Accuracy.png
  Sucide & Depression Detection/Images/Top 50 words.png
  Sucide & Depression Detection/Images/WordCloud.png
  Sucide & Depression Detection/Models/suicidal-content-detection-using-gru.ipynb
  Sucide & Depression Detection/Models/suicidal-ideation-detection-bilstm-rnn.ipynb
  Sucide & Depression Detection/README.md
Labels: gssoc, level3

#772 Calories Burnt Prediction
  Calories Burnt Prediction/Project_16_Calories_Burnt_Prediction.ipynb
  Calories Burnt Prediction/calories.csv
  Calories Burnt Prediction/exercise.csv
Labels: level1, level3

#762 Picture animater
  Picture Animater/Input Image/Amy.jpg
  Picture Animater/Output Image/AmyOP.jpeg
  Picture Animater/README.md
  Picture Animater/animate_me.ipynb
  Picture Animater/animate_me.py
  Skin Cancer Prediction/Dataset_Link
  Skin Cancer Prediction/Melanoma_SkinCancer_Detection.ipynb
  Skin Cancer Prediction/Practice_Model/PracticeModels.ipynb
  Skin Cancer Prediction/README.md
  Skin Cancer Prediction/Readme_images/DatasetPlot.png
  Skin Cancer Prediction/Readme_images/Datasetdf.png
  Skin Cancer Prediction/Readme_images/ModelArch.png
  Skin Cancer Prediction/Readme_images/ModelEvaluation.png
  Skin Cancer Prediction/Readme_images/ModelLayer.png
  Skin Cancer Prediction/Readme_images/Samleimagefromdataset.png
Labels: gssoc, level1

#788 Added Multilingual Customer Support Tickets Prediction
  Multilingual Customer Support Tickets Prediction/Dataset/ticket_helpdesk_labeled_multi_languages_english_spain_french_german.csv
  Multilingual Customer Support Tickets Prediction/Model/Multilingual_Customer_Support_Tickets_Prediction.ipynb
  Multilingual Customer Support Tickets Prediction/requirements.txt
Labels: gssoc, level3

#787 Molecule Property Prediction
  Molecular Property Prediction/Molecule_Property_Prediction.ipynb
  Molecular Property Prediction/README.md
  Molecular Property Prediction/__pycache__/mpl_rdkit_utils.cpython-311.pyc
  Molecular Property Prediction/best_val.model
  Molecular Property Prediction/input.csv
  Molecular Property Prediction/input.smi
  Molecular Property Prediction/mpl_rdkit_utils.py
Labels: gssoc, level3

#785 Android Malware Detection
  Android Security/malware.csv
  Android Security/malware_detection.ipynb
  Android Security/readme.md
Labels: gssoc, level3

#783 Added Blood Donation Prediction
  Blood Donation Prediction/Blood Glucose Level Prediction(Machine Learning).ipynb
Labels: gssoc, level1

#813 A Medical Assistance Chatbot #795 issue closed
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/.vscode/launch.json
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/__pycache__/model.cpython-38.pyc
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/__pycache__/nltk_utils.cpython-38.pyc
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/chat.py
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/chatbot_model.h5
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/classes.pkl
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/intents.json
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/model.py
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/nltk_utils.py
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/train.py
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/train_keras.py
  Medical_Assistance_Chatbot/Chatbot-main/Chatbot-main/words.pkl
Labels: gssoc, level3

#825 Loan Repayment Prediction
  Loan Repayment Prediction/Loan Prediction Datasets/test.csv
  Loan Repayment Prediction/Loan Prediction Datasets/train.csv
  Loan Repayment Prediction/Loan Prediction.ipynb
  Loan Repayment Prediction/README.md
Labels: gssoc, level3

#824 SMS Spam Classification
  SMS Spam Classification/.ipynb_checkpoints/email spam classification-checkpoint.ipynb
  SMS Spam Classification/email spam classification.ipynb
  SMS Spam Classification/model.pkl
  SMS Spam Classification/readme.md
  SMS Spam Classification/spam.csv
  SMS Spam Classification/vectorizer.pkl
Labels: gssoc, level3

#819 Cervical Cancer Prediction
  Cervical Cancer Prediction/cervical-cancer-classification.ipynb
  Cervical Cancer Prediction/readME.md
Labels: gssoc, level3

#818 Added Pima Indians Diabetes Database Prediciton
  Pima Indians Diabetes Database Prediciton/Dataset/diabetes.csv
  Pima Indians Diabetes Database Prediciton/Model/Pima_Indians_Diabetes_Database_Prediciton.ipynb
  Pima Indians Diabetes Database Prediciton/requirements.txt
Labels: gssoc, level3

#833 National Poll on Healthy Aging
  National Poll on Healthy Aging/Readme.md
  National Poll on Healthy Aging/national_poll_on_healthy_aging_model.ipynb
Labels: gssoc, level3

#836 SONAR rock vs mine Prediction
  SONAR rock vs mine prediction/Copy of sonar data.csv
  SONAR rock vs mine prediction/Copy_of_Rock_vs_Mine_Prediction.ipynb
Labels: gssoc, level3

#843 Voice identification
  Kidney Stone Prediction/Dataset/README.md
  Kidney Stone Prediction/Dataset/kidney_stone_data.csv
  Kidney Stone Prediction/Images/kid1.jpg
  Kidney Stone Prediction/Images/kid2.png
  Kidney Stone Prediction/Model/Kidney_Stone_Prediction.ipynb
  Kidney Stone Prediction/Model/README.md
  Kidney Stone Prediction/requirements.txt
  Voice Gender Identification/Dataset/README.md
  Voice Gender Identification/Dataset/voice.csv
  Voice Gender Identification/Images/voice1.png
  Voice Gender Identification/Images/voice10.png
  Voice Gender Identification/Images/voice11.png
  Voice Gender Identification/Images/voice12.png
  Voice Gender Identification/Images/voice2.png
  Voice Gender Identification/Images/voice3.png
  Voice Gender Identification/Images/voice4.png
  Voice Gender Identification/Images/voice5.png
  Voice Gender Identification/Images/voice6.png
  Voice Gender Identification/Images/voice7.png
  Voice Gender Identification/Images/voice8.png
  Voice Gender Identification/Images/voice9.png
  Voice Gender Identification/Model/README.md
  Voice Gender Identification/Model/Voice_Gender_Identification.ipynb
  Voice Gender Identification/requirements.txt
Labels: gssoc, level3

#854 Fetal Health Classification
  Fetal Health Classification/README.md
  Fetal Health Classification/fetal-health-classification.ipynb
  Fetal Health Classification/fetal_health.csv
Labels: gssoc, level3

#853 Created Air Quality Streamlit Webapp
  Air quality analysis and Health Impact score prediction/Air quality analysis and Health Impact score prediction.ipynb
  Air quality analysis and Health Impact score prediction/Webapp.py
  Air quality analysis and Health Impact score prediction/model.pkl
Labels: gssoc, level3

#851 #821 Added Cardiovascular Disease analysis and detection
  Cardiovascular Disease Analysis and Prediction/Dataset/dataset.csv
  Cardiovascular Disease Analysis and Prediction/Images/age_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/chestpain_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/correlation_heatmap.png
  Cardiovascular Disease Analysis and Prediction/Images/exerciseangia_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/fastingbloodsugar_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/gender_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/maxheartrate_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/noofmajorvessels_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/oldpeak_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/restingBP_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/restingrelectro_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/serumcholestrol_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/slope_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/target_correlation.png
  Cardiovascular Disease Analysis and Prediction/Images/target_feature.png
  Cardiovascular Disease Analysis and Prediction/Model/cardiovascular-disease-analysis-and-prediction.ipynb
  Cardiovascular Disease Analysis and Prediction/README.md
Labels: gssoc, level3

#848 Added Foreign Exchange Rate Prediction model
  Foreign Exchange Rate Prediction/Foreign_Exchange_Rates.csv
  Foreign Exchange Rate Prediction/LSTM_model.ipynb
  Foreign Exchange Rate Prediction/Readme.md
Labels: gssoc, level2

#840 Ammonium prediciton in river water
  Ammonium Prediction In River Water/Ammonium Prediction in River Water.ipynb
  Ammonium Prediction In River Water/README.md
Labels: gssoc, level3

#835 Human Dataset Visualization
  Human3.6M_dataset_visualization/Data_generator_visualization.py
  Human3.6M_dataset_visualization/README.md
  Human3.6M_dataset_visualization/directions0.png
Labels: gssoc, level3

#870 SmartPhone Processor Classification
  Smartphone processor classification/Images/Matrix model 1.png
  Smartphone processor classification/Images/Matrix model 2.png
  Smartphone processor classification/Images/Visualization model 1.png
  Smartphone processor classification/Images/Visualization model 2.png
  Smartphone processor classification/Images/Visualization model 3.png
  Smartphone processor classification/Images/matrix model 3.png
  Smartphone processor classification/dataset/ML_ALL_benchmarks.csv
  Smartphone processor classification/dataset/antutu_android_vs_ios_v4.csv
  Smartphone processor classification/dataset/smartphone_cpu_stats.csv
  Smartphone processor classification/model/ML_ALL_benchmarks.csv
  Smartphone processor classification/model/Ranking.ipynb
  Smartphone processor classification/readme.md
  Smartphone processor classification/requirements.txt
Labels: gssoc, level3

#898 Added Body Fat Prediction
  Body Fat Prediction/BodyFatPrediction.ipynb
  Body Fat Prediction/Feature_Importance_score.ipynb
  Body Fat Prediction/Feature_importance.md
  Body Fat Prediction/Feature_importance_analysis.ipynb
  Body Fat Prediction/README.md
  Body Fat Prediction/bodyfat.csv
Labels: gssoc, level3

#897 Added Instagram Reach prediction
  Instagram Reach prediction/Insta_Reach_Algorithm.ipynb
  Instagram Reach prediction/Readme.md
  Instagram Reach prediction/instagram_reach.txt
Labels: gssoc, level3

#880 HeartBeat Classification using ECG
  Heartbeat Classification using ECG/Dataset/README.md
  Heartbeat Classification using ECG/Images/00.png
  Heartbeat Classification using ECG/Images/01.png
  Heartbeat Classification using ECG/Images/02.png
  Heartbeat Classification using ECG/Images/03.png
  Heartbeat Classification using ECG/Images/04.png
  Heartbeat Classification using ECG/Images/05.png
  Heartbeat Classification using ECG/Images/06.png
  Heartbeat Classification using ECG/Images/07.png
  Heartbeat Classification using ECG/Images/08.png
  Heartbeat Classification using ECG/Images/09.png
  Heartbeat Classification using ECG/Images/10.png
  Heartbeat Classification using ECG/Images/11.png
  Heartbeat Classification using ECG/Images/12.png
  Heartbeat Classification using ECG/Images/13.png
  Heartbeat Classification using ECG/Images/14.png
  Heartbeat Classification using ECG/Model/README.md
  Heartbeat Classification using ECG/Model/ecg-cnn-model01.ipynb
  Heartbeat Classification using ECG/requirements.txt
Labels: gssoc, level3

#881 Song Clustering Project
  Song Clustering/README.md
  Song Clustering/model.ipynb
Labels: gssoc, level3

#871 Added Parkinson Disease Detection
  Parkinson Disease Detection/README.md
  Parkinson Disease Detection/_config.yml
  Parkinson Disease Detection/algorithm_comparison.py
  Parkinson Disease Detection/algorithm_comparison_praat.py
  Parkinson Disease Detection/benchmark.py
  Parkinson Disease Detection/data.csv
  Parkinson Disease Detection/index.html
  Parkinson Disease Detection/knn.py
  Parkinson Disease Detection/parkinsons.csv
  Parkinson Disease Detection/rescaled_data_algorithm_comparison.py
Labels: gssoc, level3

#775 Sign Language Interpreter
  Sign Language Interpreter/Models/DS_Store
  Sign Language Interpreter/Models/Rotate_images.py
  Sign Language Interpreter/Models/cnn_model_train.py
  Sign Language Interpreter/Models/create_gestures.py
  Sign Language Interpreter/Models/display_gestures.py
  Sign Language Interpreter/Models/final.py
  Sign Language Interpreter/Models/gesture_db.db
  Sign Language Interpreter/Models/hist
  Sign Language Interpreter/Models/load_images.py
  Sign Language Interpreter/Models/set_hand_histogram.py
  Sign Language Interpreter/README.md
  Sign Language Interpreter/requirement.txt
Labels: gssoc, level3

#862 Added: Fast Food Nutrition Analysis
  Fast Food Nutrition Analysis/FastFoodNutritionMenu.csv
  Fast Food Nutrition Analysis/README.md
  Fast Food Nutrition Analysis/fast-food-nutrition-analysis.ipynb
Labels: gssoc, level3

#861 KNN algorithm visualizer tool
  KNN-Visualizer-main/Home.py
  KNN-Visualizer-main/README.md
  KNN-Visualizer-main/pages/1_Regressor.py
  KNN-Visualizer-main/pages/2_Hyperparameter.py
Labels: gssoc, level3

#900 Added Security camera ai
  security_camera_ai/README.md
  security_camera_ai/app/favicon.ico
  security_camera_ai/app/globals.css
  security_camera_ai/app/layout.tsx
  security_camera_ai/app/page.tsx
  security_camera_ai/components.json
  security_camera_ai/components/social-links.tsx
  security_camera_ai/components/theme-provider.tsx
  security_camera_ai/components/theme-toggle.tsx
  security_camera_ai/components/ui/button.tsx
  security_camera_ai/components/ui/dropdown-menu.tsx
  security_camera_ai/components/ui/popover.tsx
  security_camera_ai/components/ui/separator.tsx
  security_camera_ai/components/ui/slider.tsx
  security_camera_ai/components/ui/sonner.tsx
  security_camera_ai/lib/utils.ts
  security_camera_ai/next.config.js
  security_camera_ai/package-lock.json
  security_camera_ai/package.json
  security_camera_ai/postcss.config.js
  security_camera_ai/public/next.svg
  security_camera_ai/public/vercel.svg
  security_camera_ai/tailwind.config.js
  security_camera_ai/tailwind.config.ts
  security_camera_ai/tsconfig.json
  security_camera_ai/utils/audio.ts
  security_camera_ai/utils/draw.ts
Labels: gssoc, level3

#879 Added Emotion_Recognition_from_Audio
  Emotion_Recognition_using_DeepLearning/README.md
  Emotion_Recognition_using_DeepLearning/main.ipynb
  Emotion_Recognition_using_DeepLearning/requirements.txt
Labels: gssoc, level3

#845 Exoplanet Detection
  Exoplanet Detection/Dataset/readme.md
  Exoplanet Detection/exoplanet.ipynb
  Exoplanet Detection/readme.md
Labels: gssoc, level3

#905 Wine Quality Prediction using Linear Regression
  README.md
  WineQT.csv
  Wine_Quality_Prediction.ipynb
Labels: gssoc, level3

#906 Added Multiple Disease Predictor
  Multiple Disease Predictor/README.md
  Multiple Disease Predictor/app.py
  Multiple Disease Predictor/dataset/diabetes.csv
  Multiple Disease Predictor/dataset/heart.csv
  Multiple Disease Predictor/dataset/kidney_disease.csv
  Multiple Disease Predictor/notebooks/Advance Project Diabetes Prediction Using ML.ipynb
  Multiple Disease Predictor/notebooks/Advance Project Heart Disease Prediction Using ML.ipynb
  Multiple Disease Predictor/notebooks/Advance Project Kidney Disease Prediction Using ML.ipynb
  Multiple Disease Predictor/saved_models/diabetes.pkl
  Multiple Disease Predictor/saved_models/heart.pkl
  Multiple Disease Predictor/saved_models/kidney.pkl
Labels: gssoc, level3

#920 Adding Prediction of Credit Card Approval
  CreditCardApproval.ipynb
  Readme for Credit Card Approval.md
  datasets/cc_approvals.data
Labels: gssoc, level3

#919 Add Diwali Sales Analysis Project
  Diwali Sales Analysis/Diwali Sales Data.csv
  Diwali Sales Analysis/Diwali_Sales_Analysis.ipynb
  Diwali Sales Analysis/README.md
Labels: gssoc, level3

#917 Adding Dissolved oxygen prediction in river water ml model
  Dissolved oxygen prediction in river water/Dataset/test.csv
  Dissolved oxygen prediction in river water/Dataset/train.csv
  Dissolved oxygen prediction in river water/Dissolved oxygen prediction.ipynb
Labels: gssoc, level3

#916 Added Daily Birth Fore Casting
  Daily Births Forecasting Prediction using Facebook Prophet/Daily_Births_Forecasting_Prediction_using_Facebook_Prophet.ipynb
  Daily Births Forecasting Prediction using Facebook Prophet/README.md
  Daily Births Forecasting Prediction using Facebook Prophet/daily-total-female-births-CA.csv
Labels: gssoc, level3

#915 Smile recognition with deep learning
  Smile Recognition with Deep Learning/Dataset/Readme.md
  Smile Recognition with Deep Learning/Images/Readme.md
  Smile Recognition with Deep Learning/Images/Screenshot (372).png
  Smile Recognition with Deep Learning/Images/cnn.png
  Smile Recognition with Deep Learning/Images/densenet.png
  Smile Recognition with Deep Learning/Images/test.png
  Smile Recognition with Deep Learning/Images/traing.png
  Smile Recognition with Deep Learning/Models/Readme.md
  Smile Recognition with Deep Learning/Models/cnn-smile.ipynb
  Smile Recognition with Deep Learning/Models/densenet.ipynb
  Smile Recognition with Deep Learning/requirements.txt
Labels: gssoc, level3

#912 IRIS-Flower-Classification
  IRIS-Flower-Classification-main/IRIS_Flower_classification.ipynb
  IRIS-Flower-Classification-main/README.md
  IRIS-Flower-Classification-main/iris.csv
Labels: gssoc, level3

#907 For labels
  Linear Regression Model/linear_regression.py
Labels: gssoc, level3

#909 Add PNEUMONIA DETECTOR
  PNEUMONIA DETECTOR/Flask Application/app.py
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-grid.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-grid.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-grid.min.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-grid.min.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-reboot.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-reboot.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-reboot.min.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap-reboot.min.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap.min.css
  PNEUMONIA DETECTOR/Flask Application/static/css/bootstrap.min.css.map
  PNEUMONIA DETECTOR/Flask Application/static/css/font-awesome.min.css
  PNEUMONIA DETECTOR/Flask Application/static/css/main.css
  PNEUMONIA DETECTOR/Flask Application/static/css/normalize.css
  PNEUMONIA DETECTOR/Flask Application/static/css/style.css
  PNEUMONIA DETECTOR/Flask Application/static/css/test.css
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.bundle.js
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.bundle.js.map
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.bundle.min.js
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.bundle.min.js.map
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.js
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.js.map
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.min.js
  PNEUMONIA DETECTOR/Flask Application/static/js/bootstrap.min.js.map
  PNEUMONIA DETECTOR/Flask Application/static/js/jquery.min.js
  PNEUMONIA DETECTOR/Flask Application/static/js/main.js
  PNEUMONIA DETECTOR/Flask Application/static/js/newjs.js
  PNEUMONIA DETECTOR/Flask Application/static/js/plugins.js
  PNEUMONIA DETECTOR/Flask Application/static/js/vendor/jquery-1.12.0.min.js
  PNEUMONIA DETECTOR/Flask Application/static/js/vendor/modernizr-2.8.3.min.js
  PNEUMONIA DETECTOR/Flask Application/tempCodeRunnerFile.py
  PNEUMONIA DETECTOR/Flask Application/templates/import.html
  PNEUMONIA DETECTOR/Flask Application/templates/index.html
  PNEUMONIA DETECTOR/Flask Application/uploads/IM-0005-0001.jpeg
  PNEUMONIA DETECTOR/Flask Application/uploads/person1_virus_6.jpeg
  PNEUMONIA DETECTOR/Pneumonia Detection Using Deep Learning.ipynb
  PNEUMONIA DETECTOR/README.md
Labels: gssoc, level3

#933 System for predicting whether an object is either Rock or Mine with SONAR data
  SONAR Classifier/Sonar_Classifier .ipynb
  SONAR Classifier/sonar_data1.csv
Labels: gssoc, level3

#941 Added Skin Disease Predictor
  Skin Disease Predictor/Readme.md
  Skin Disease Predictor/skin-disease-inception.ipynb
Labels: level2

#943 Speech Sentiment analysis using DL
  Speech Sentiment Analysis using DL/Dataset/README.md
  Speech Sentiment Analysis using DL/Images/DENSENET121 Accuracy.png
  Speech Sentiment Analysis using DL/Images/DENSENET121 Loss.png
  Speech Sentiment Analysis using DL/Images/EfficientNetB7 Accuracy.png
  Speech Sentiment Analysis using DL/Images/EfficientNetB7 Loss.png
  Speech Sentiment Analysis using DL/Images/InceptionV3 Accuracy.png
  Speech Sentiment Analysis using DL/Images/InceptionV3 Loss.png
  Speech Sentiment Analysis using DL/Images/Negative EDA.png
  Speech Sentiment Analysis using DL/Images/Neutral EDA.png
  Speech Sentiment Analysis using DL/Images/Positive EDA.png
  Speech Sentiment Analysis using DL/Images/RESNET50 Accuracy.png
  Speech Sentiment Analysis using DL/Images/RESNET50 Loss.png
  Speech Sentiment Analysis using DL/Images/VGG16 Accuracy.png
  Speech Sentiment Analysis using DL/Images/VGG16 Loss.png
  Speech Sentiment Analysis using DL/Images/Xception Accuracy.png
  Speech Sentiment Analysis using DL/Images/Xception Loss.png
  Speech Sentiment Analysis using DL/Model/speech-sentiment-analysis.ipynb
  Speech Sentiment Analysis using DL/README.md
Labels: gssoc, level3

#946 For labels
  Linear Regression Model/linear_regression.py
Labels: gssoc, level2

#976 added AI Trading Simulator
  Algorithm Trading Simulator/Readme.MD
  Algorithm Trading Simulator/requirements.txt
  Algorithm Trading Simulator/simulator.py
Labels: gssoc, level3

#793 Added cancer prediction model
  Cancer Prediction Model/ProjectPredictCancer.ipynb
  Cancer Prediction Model/README.md
  Cancer Prediction Model/deploy.pkl
  Cancer Prediction Model/file.py
Labels: gssoc, level1

#966 Farm's Biogas ML Prediction(Livestock)
  Farm Biogas ML Prediction - Copy/Farm's_Biogas_ML_Prediction(Livestock).ipynb
  Farm Biogas ML Prediction - Copy/README.md
  Farm Biogas ML Prediction - Copy/veri_seti_son_2.csv
  Farm Biogas ML Prediction/Farm's_Biogas_ML_Prediction(Livestock).ipynb
  Farm Biogas ML Prediction/README.md
  Farm Biogas ML Prediction/veri_seti_son_2.csv
  Rain Prediction/README.md
  Rain Prediction/Rain_Prediction.ipynb
  Rain Prediction/weatherAUS.csv.zip
Labels: gssoc, level3

#962 Logistic Regression Algorithm Visualizer Tool
  Visualise-Logistic-master/Procfile
  Visualise-Logistic-master/README.md
  Visualise-Logistic-master/logistic-app.py
  Visualise-Logistic-master/requirements.txt
  Visualise-Logistic-master/setup.sh
Labels: gssoc, level3

#960 PR merged but not labeled issue
  ML
Labels: gssoc, level3

#956 Added Timeline Analysis: Covid-19 Project
  Timeline Analysis Covid-19/COVID19 Analysis.ipynb
  Timeline Analysis Covid-19/README.md
Labels: gssoc, level3

#951 Create README.MD
  Air quality analysis and Health Impact score prediction/README.MD
Labels: gssoc, level1

#950 Update README.md
  AI_CHATBOT/README.md
Labels: gssoc, level1

#980 Micro Gas Turbine Energy Prediction
  Micro Gas Turbine Energy Detector/dataset_micro_gas_turbine.zip
  Micro Gas Turbine Energy Detector/energy.ipynb
  Micro Gas Turbine Energy Detector/readme.md
Labels: gssoc, level3

#981 Implementation of different learning rules in ann
  Learning Rules In ANN/Learning-Rules.md
  Learning Rules In ANN/learning_rules.ipynb
Labels: gssoc, level3

#670 Epidemic outbreaks predictions
  Covid_prediction.ipynb
  time_series_covid19_confirmed_global.csv
  time_series_covid19_deaths_global.csv
  time_series_covid19_recovered_global.csv
Labels: gssoc, level1

#1006 Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/5-Figure2-1.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/5-Figure3-1.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/5-Figure4-1.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/5-Figure5-1.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Foot_C.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Foot_K.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Foot_in.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Lung_C.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Lung_K.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Lung_in.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/Paper_1_1.jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Benchmark Paper_Figures/readme.md
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (1).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (12).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (14).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (15).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (2).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/1 (7).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Foot_CMeans.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Foot_Input.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Foot_KMeans.PNG
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Lung_CMeans.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Lung_Input.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Lung_KMeans.png
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Paper_1.jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/Paper_3.jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Benchmark/readme.md
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/Wallpapers 1366x768 (1).jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/bg.jpg
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/cancer.fig
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/cancer.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_FM2map.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_FastFCMeans.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_KMeans.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_LUT2label.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_find_best_cluster.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_kmeans2.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/fun_kmeans3.m
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/Bone-Cancer-Detection/readme.md
  Bone-Cancer-Detection-GUI-in-Matlab-using-Image-Processing-Techniques-main/README.md
Labels: gssoc, level3

#1005 Update readme.md
  Apriori- Market Basket Analysis/readme.md
Labels: gssoc, level1

#1004 Create README.MD
  .ipynb_checkpoints/README.MD
Labels: gssoc, level1

#1015 Plant growth analysis and prediction
  Plant growth analysis and prediction/Dataset/plant_growth_data.csv
  Plant growth analysis and prediction/plant_growth.ipynb
Labels: gssoc, level3

#1018 Normal Distribution vs t-Distribution Visualization Tool
  normal-distribution-vs-t-distribution-master/.idea/.gitignore
  normal-distribution-vs-t-distribution-master/.idea/ci3.iml
  normal-distribution-vs-t-distribution-master/.idea/inspectionProfiles/Project_Default.xml
  normal-distribution-vs-t-distribution-master/.idea/inspectionProfiles/profiles_settings.xml
  normal-distribution-vs-t-distribution-master/.idea/misc.xml
  normal-distribution-vs-t-distribution-master/.idea/modules.xml
  normal-distribution-vs-t-distribution-master/app.py
  normal-distribution-vs-t-distribution-master/requirements.txt
Labels: gssoc, level3

#1017 Impact of Mental Health on Tech: EDA and Analysis
  .ipynb_checkpoints/Mental_Health_Impact.ipynb
Labels: gssoc, level3

#1014 Radar Return Classification from the Ionosphere
  Radar Return Classification from the Ionosphere/ionosphere.ipynb
Labels: gssoc, postman

#1012 Camera Covering Prediction
  Camera Covering Prediction/README.md
  Camera Covering Prediction/main.py
Labels: gssoc, level3

#1010 Added activation function in ann
  Activation Function/Activation Function.md
  Activation Function/activation_functions.ipynb
Labels: gssoc, level3

#1036 Add FCNN model
  Weather_Prediction_With_DL_Model.ipynb
Labels: gssoc, level3

#1035 added animal classification model using CNN
  Animal Classification using CNN/animal_classification.ipynb
  Animal Classification using CNN/readme.md
Labels: gssoc, level1
