Repository recodehive/machine-learning-repos, pull requests merged in 2024-06, with the labels that each got.

#91 Transfer Learning with VGG16 and ResNet
  Transfer Learning with VGG16 and ResNet/Readme.md
  Transfer Learning with VGG16 and ResNet/Transfer_Learning_with_VGG16_and_ResNet.ipynb
Labels: gssoc, level1

#88 Adding Linear Regression Model- Solved issue #86
  Linear Regression Model/Salary_dataset.csv
  Linear Regression Model/linear_regression.py
Labels: gssoc, level1

#43 added Car Price Prediction Using Machine Learning [Issue #42]
  Car Price Prediction Using Machine Learning/CAR PRIZE PREDICTION USING MACHINE LEARNING.ipynb
  Email Spam Detection/EMAIL SPAM DETECTION WITH MACHINE LEARNING.ipynb
Labels: gssoc, level1

#50 Hand Digit Recognition Using Convolutional Neural Network(CNN): #2
  Hand_Digit_Recognition/hand_digit_recognition.ipynb
  Hand_Digit_Recognition/readme.md
Labels: gssoc, level1

#55 Activation Function and Loss Function in Neural Network: #18
  Activation_and_Loss_function/Readme.md
Labels: gssoc

#74 Regression in Machine Learning: #15
  Regressions/Readme.md
  Regressions/linear_regression.ipynb
Labels: gssoc, level1

#83 Added a powerful new tool to the Parkinson's disease prediction model…
  Parkinsons-Disease-Detector-main/PARKINSON'S_DETECTION (1).ipynb
  Parkinsons-Disease-Detector-main/README.md
Labels: gssoc, level1

#85 Optimizers in Machine Learning: #19
  Optimizers/Readme.md
Labels: gssoc

#99 Multiple Linear Regression on Student Performance
  Linear Regression Model/Student_Performance.csv
  Linear Regression Model/Student_Performance.ipynb
Labels: gssoc, level1

#102 Added Cricket Shots Detection
  Cricket Shots Detection/README.md
  Cricket Shots Detection/dataset/README.md
  Cricket Shots Detection/images/bar.png
  Cricket Shots Detection/images/dense.png
  Cricket Shots Detection/images/eda_cric.png
  Cricket Shots Detection/images/efficient.png
  Cricket Shots Detection/images/inception.png
  Cricket Shots Detection/images/pie chart.png
  Cricket Shots Detection/images/resnet.png
  Cricket Shots Detection/model/cricket shots.ipynb
  Cricket Shots Detection/requirements.txt
Labels: gssoc, level1

#124 Diabetes prediction (Using Machine Learning Algorithms) #118
  Diabetes prediction (Machine Learning Algorithms)/Diabetes.ipynb
  Diabetes prediction (Machine Learning Algorithms)/deeplearning.pkl
  Diabetes prediction (Machine Learning Algorithms)/diabetes.csv
  Diabetes prediction (Machine Learning Algorithms)/lr .pkl
  Diabetes prediction (Machine Learning Algorithms)/requirements.txt
  Diabetes prediction (Machine Learning Algorithms)/scaler .pkl
Labels: gssoc, level1

#116 Credit Card Fraud Detection Model
  Credit card fraud detection/.gitkeep
  Credit card fraud detection/credit_card_fraud_detection.ipynb
Labels: gssoc, level1

#98 Solved issue #95- KNN Regression Model
  KNN Regression/KNN_regression.py
  KNN Regression/Salary_dataset.csv
Labels: gssoc, level1

#150 Migraine Type Prediction Model
  Migraine Type Prediction System/Migraine Prediction System.ipynb
  Migraine Type Prediction System/migraine_data.csv
  Migraine Type Prediction System/migraine_trained_model.sav
Labels: gssoc, level1

#101 Update readme.md
  Support_Vector_Machine/readme.md
Labels: gssoc

#120 Placement_Predictor
  Placement_Predictor/Placement_Analysis.ipynb
  Placement_Predictor/README.md
  Placement_Predictor/Untitled.ipynb
  Placement_Predictor/datasets/Placement_Data_Full_Class.csv
  Placement_Predictor/datasets/merged_placement_data.csv
  Placement_Predictor/datasets/placement-dataset.csv
  Placement_Predictor/main.py
  Placement_Predictor/merged_app.py
  Placement_Predictor/requirements.txt
Labels: gssoc, level1

#160 Adding Autoregressive Integrated Moving Average model to close #156
  ARIMA/arima.py
Labels: gssoc, level1

#158 Time Series Forecasting on Global Warming
  Time Series Forecasting on Global Warming/EDA - Time Series Forecasting on Global Warming Trends.ipynb
  Time Series Forecasting on Global Warming/Max_Min_Dataset.csv
  Time Series Forecasting on Global Warming/long_format_annual_surface_temp.csv
  Time Series Forecasting on Global Warming/wide_format_annual_surface_temp.csv
Labels: gssoc, level1

#108 Movie Recommendation System
  movierecommendation1.ipynb
Labels: gssoc, level1

#180 PR NO. - #143 [Feature] --> Face mask detection using deep learning
  Face_Mask_Detection/Face_Mask_Detection.ipynb
  Face_Mask_Detection/README.md
  Face_Mask_Detection/Test/.ipynb_checkpoints/image1-checkpoint.jpg
  Face_Mask_Detection/Test/image1.jpg
  Face_Mask_Detection/Test/image2.jpg
  Face_Mask_Detection/Test/image3.jpg
Labels: gssoc, level1

#179 Machine Learning - Roadmaps and Resources :Adding ML Roadmap and Resources
  Machine Learning - Roadmap and Resources/readme.md
Labels: gssoc, level1

#176 streamlit-with-gradio-api
  streamlit-with-gradio-api/README.md
  streamlit-with-gradio-api/app.py
Labels: gssoc, level1

#175 Health Track
  Health care/Apps/Breast_Cancer.py
  Health care/Apps/Diabetes.py
  Health care/Apps/Heart_Disease.py
  Health care/Apps/Hypertension_App.py
  Health care/Apps/Kidney_App.py
  Health care/Apps/Stroke_App.py
  Health care/Apps/__pycache__/Breast_Cancer.cpython-310.pyc
  Health care/Apps/__pycache__/Breast_Cancer.cpython-312.pyc
  Health care/Apps/__pycache__/Diabetes.cpython-310.pyc
  Health care/Apps/__pycache__/Diabetes.cpython-312.pyc
  Health care/Apps/__pycache__/Heart_Disease.cpython-310.pyc
  Health care/Apps/__pycache__/Heart_Disease.cpython-312.pyc
  Health care/Apps/__pycache__/Hypertension_App.cpython-310.pyc
  Health care/Apps/__pycache__/Hypertension_App.cpython-312.pyc
  Health care/Apps/__pycache__/Kidney_App.cpython-310.pyc
  Health care/Apps/__pycache__/Kidney_App.cpython-312.pyc
  Health care/Apps/__pycache__/Stroke_App.cpython-310.pyc
  Health care/Apps/__pycache__/Stroke_App.cpython-312.pyc
  Health care/Apps/__pycache__/Type2_Diabetes.cpython-310.pyc
  Health care/Home.py
  Health care/Run_command.py
Labels: gssoc, level1

#202 Heart Failure Prediction
  Heart Failure Prediction/heart-failure-prediction.ipynb
  Heart Failure Prediction/heart.csv
Labels: gssoc, level1

#196 Customer Churn Prediction
  Customer_churn_walmart.ipynb
Labels: gssoc, level1

#195 Adding Apriori project files
  Apriori- Market Basket Analysis/Apriori.ipynb
  Apriori- Market Basket Analysis/apriori.py
  Apriori- Market Basket Analysis/info.docx
Labels: gssoc

#194 #129 Sentiment Analysis of IMDB Movie Reviews
  Sentiment Analysis of IMDB dataset/README.md
  Sentiment Analysis of IMDB dataset/sentiment-analysis-of-imdb-movie-reviews.ipynb
Labels: gssoc, level1

#193 Added content on PCA
  Principal Component Analysis/pca.py
  Principal Component Analysis/readme.md
Labels: gssoc

#148 Wine Quality Detector
  Winequality_red/README.md
  Winequality_red/winequality-red.csv
  Winequality_red/winequality-red.xlsx
  Winequality_red/winequality_red.ipynb
Labels: gssoc, level1

#106 Added a neural network model for iris flower classification with 96% …
  Email Spam Detection/README.md
  iris_classification/nn_iris_classification .ipynb
  iris_classification/readme.md
  irony_sarcasm_detection/README.md
Labels: gssoc, level1

#162 MNIST_Fashion_Classifier
  MNIST_Fashion_Classifier/Fashion_MNIST_classifier.ipynb
  MNIST_Fashion_Classifier/README.md
  MNIST_Fashion_Classifier/mnistFashion_network.pt
  MNIST_Fashion_Classifier/trained_model.pth
Labels: gssoc, level1

#183 updated readme file
  README.md
Labels: help wanted, gssoc

#182 Github-Automated-Analysis
  Github-Automated-Analysis/.gitignore
  Github-Automated-Analysis/main.py
  Github-Automated-Analysis/repo_data.csv
  Github-Automated-Analysis/utils/config.py
  Github-Automated-Analysis/utils/constants.py
Labels: gssoc, level1

#213 Update README.md
  README.md
Labels: gssoc, level1

#212 Air Quality Prediction using ML
  AirQualityPrediction.ipynb
Labels: gssoc, level1

#226 Movie Recommendation system
  Movie Recommendation system/MovieRecommendation.ipynb
  Movie Recommendation system/Readme.md
Labels: gssoc, level1

#224 Model Performance Monitoring System
  Model Performance Monitoring System/## Readme.md
  Model Performance Monitoring System/Model_Performance_Monitoring_System.ipynb
Labels: gssoc, level1

#233 Spoken Language Translator
  Spoken Language Translator/README.MD
  Spoken Language Translator/translator.py
  Tesla Stock Price Prediction Using Prophet/README.md
  Tesla Stock Price Prediction Using Prophet/Tesla_stock_prediction_using_FB_Prophet.ipynb
Labels: gssoc, level1

#232 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#231 Add spam mail detection
  Spam Mail Classifier/README.md
  Spam Mail Classifier/Spam_Mail_Prediction_using_Machine_Learning (1).ipynb
Labels: gssoc, level1

#240 Add Dementia prediction
  Dementia_Detection/Dementia_detection.ipynb
  Dementia_Detection/content/oasis_cross-sectional.csv
  Dementia_Detection/content/oasis_longitudinal.csv
Labels: gssoc, level1

#238 Email_spam_classifier for issue #237
  emailspamclassifier/app.py
  emailspamclassifier/background.png
  emailspamclassifier/email.pkl
  emailspamclassifier/email_icon.png
  emailspamclassifier/mail_data.csv
  emailspamclassifier/requirements.txt
  emailspamclassifier/spammer.py
  emailspamclassifier/vectorizer.pkl
  emailspamclassifier/vectorizer1.pkl
  emailspamclassifier/vectorizer2.pkl
Labels: gssoc, level1

#234 Add wine quality prediction
  Wine quality prediction/README.md
  Wine quality prediction/Wine_Quality_Prediction_using_Machine_Learning_with_Python.ipynb
Labels: gssoc, level1

#263 Added Stock Price Prediction machine learning project
  Stock_Price_Prediction/README.md
  Stock_Price_Prediction/stock_price_prediction.ipynb
Labels: gssoc, level1

#241 Add house price prediction
  House Price Prediction/House_Price_Prediction.ipynb
  House Price Prediction/README.md
Labels: gssoc, level1

#262 Added UNet model using PyTorch
  UNet_in_PyTorch/UNet.md
  UNet_in_PyTorch/UNet_from_scratch_PyTorch.ipynb
Labels: gssoc, level1

#245 AI CHATBOT addition
  AI_CHATBOT/README.md
  AI_CHATBOT/chat.py
  AI_CHATBOT/data.pth
  AI_CHATBOT/intents.json
  AI_CHATBOT/model.py
  AI_CHATBOT/nitkutils.py
  AI_CHATBOT/nltk_utils.py
  AI_CHATBOT/train.py
  Laptop-Price-Predictor/Procfile.txt
  Laptop-Price-Predictor/app.py
  Laptop-Price-Predictor/count=0.py
  Laptop-Price-Predictor/df.pkl
  Laptop-Price-Predictor/laptop-price-predictor.ipynb
  Laptop-Price-Predictor/laptop_data.csv
  Laptop-Price-Predictor/pipe.pkl
  Laptop-Price-Predictor/setup.sh
Labels: gssoc, level1

#259 Documentation/labeling tools
  Labelling Tools/Labeling Tools in Object Detection.docx
Labels: gssoc, level1

#258 ADDING New project : Object Detection and Counting in retail sector
  Retail Object Detection and Counting using YoloV8 and YoloNas/YOLO NAS Model Architecture.docx
  Retail Object Detection and Counting using YoloV8 and YoloNas/YOLO V8 Model Architecture.docx
  Retail Object Detection and Counting using YoloV8 and YoloNas/YOLO_NAS_Object_Detection.ipynb
  Retail Object Detection and Counting using YoloV8 and YoloNas/YOLO_V8_Object_Detection.ipynb
Labels: gssoc, level1

#247 Brain Tumor Detection System Implementation (Issue #210)
  Breast Cancer Detection/Dataset/README.md
  Breast Cancer Detection/Images/Confusion Matrices.png
  Breast Cancer Detection/Images/Demo webpage.png
  Breast Cancer Detection/Images/MLP.png
  Breast Cancer Detection/Images/ResNet50.png
  Breast Cancer Detection/Images/VGG16.png
  Breast Cancer Detection/Model/Model.ipynb
  Breast Cancer Detection/Model/README.md
  Breast Cancer Detection/README.md
  Breast Cancer Detection/Webapp/README.md
  Breast Cancer Detection/Webapp/static/style.css
  Breast Cancer Detection/Webapp/templates/index.html
  Breast Cancer Detection/Webapp/webapp.py
  Breast Cancer Detection/requirements.txt
Labels: gssoc, level1

#243 Pharmaceutical Drugs and Vitamins Images Detection
  Pharmaceutical Drugs and Vitamins Images Detection/Dataset/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/87918c94-5dc8-410e-94f0-fd1f8d08ebff.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/992a7274-9ea6-4757-ad0a-7c4e41805fae.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/dfb74364-4379-4131-ae23-73e3c5e80d06.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/f508171e-a64c-4b62-b1ed-9ce1fddb74c6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/02509165-66d3-4164-8f0d-1c6a8b57536a.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/385088f1-0165-4ede-a392-c686b0904e29.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/856f6215-1ccf-421a-be41-bdc7817b1590.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/dd0bc14e-65d1-4726-979e-e89d2386a6eb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/18b4bf42-2e21-4cd3-afc3-e7c672422e6e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/20fd282c-2edc-48ce-8a52-c7d87a5089cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/982a84ee-788a-4bb2-89d5-4304a8a56eac.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/c35dcb78-6440-4864-98a6-3a2ea4cebb1b.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/13e67132-466a-472b-877e-0ed951a2809e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/2d50be9e-1915-43a9-87ec-486c5d8c8ef5.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/3581db0f-bd7f-46d5-a93e-d47baced07bd.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/eb57435f-2201-4f0b-98da-b790e13750a6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/1c85d549-30b2-4d7d-b720-85eb84ab1644.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/773ea5a9-7573-4057-968e-4fa8926af4cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/976ab080-7145-4f37-aa6a-73713f8a6a9e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/ed06fe5c-e8a8-42d4-8d38-11da2ac72202.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/bar.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/image_path_distribution.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/pie_chart.png
  Pharmaceutical Drugs and Vitamins Images Detection/Models/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Models/models_Pharmaceutical_Drugs_and_Vitamins_Images_Detection_(1).ipynb
  Pharmaceutical Drugs and Vitamins Images Detection/requirement.txt
Labels: gssoc, level1

#270 Add breast cancer classification
  Breast Cancer Classification/Breast_Cancer_Classification_using_Machine_Learning.ipynb
  Breast Cancer Classification/README.md
Labels: gssoc, level1

#127 feat: added k-mean Cluster
  k_mean_algorithum/intro_of_k_mean.md
  k_mean_algorithum/k-mean-Clustering.py
Labels: gssoc, level1

#275 Adding T-20 World Cup Target Score Predictor
  T-20 World Cup Predictor/T-20 predictor.ipynb
Labels: gssoc, level1

#274 added recommendation system to market basket analysis
  Apriori- Market Basket Analysis/Apriori.ipynb
  Apriori- Market Basket Analysis/data.csv
  Apriori- Market Basket Analysis/readme.md
Labels: gssoc, level1

#273 Conduct a Preliminary Data Analysis of COVID-19 Trends and Patterns in Different Countries
  Covid19_EDA.ipynb
Labels: gssoc, level1

#272 Brain Tumor Detection using DL (Issue #210)
  Brain Tumor Detectin using DL/Dataset/README.md
  Brain Tumor Detectin using DL/Images/README.md
  Brain Tumor Detectin using DL/Images/image-1.png
  Brain Tumor Detectin using DL/Images/image-10.png
  Brain Tumor Detectin using DL/Images/image-11.png
  Brain Tumor Detectin using DL/Images/image-2.png
  Brain Tumor Detectin using DL/Images/image-3.png
  Brain Tumor Detectin using DL/Images/image-4.png
  Brain Tumor Detectin using DL/Images/image-5.png
  Brain Tumor Detectin using DL/Images/image-6.png
  Brain Tumor Detectin using DL/Images/image-7.png
  Brain Tumor Detectin using DL/Images/image-8.png
  Brain Tumor Detectin using DL/Images/image-9.png
  Brain Tumor Detectin using DL/Images/image.png
  Brain Tumor Detectin using DL/Images/image12.png
  Brain Tumor Detectin using DL/Model/README.md
  Brain Tumor Detectin using DL/Model/brain_tumor_model.ipynb
  Brain Tumor Detectin using DL/README.md
  Brain Tumor Detectin using DL/Web App/Final.mp4
  Brain Tumor Detectin using DL/Web App/README.md
  Brain Tumor Detectin using DL/Web App/Screenshot 2024-05-13 221628.png
  Brain Tumor Detectin using DL/Web App/app.py
  Brain Tumor Detectin using DL/Web App/requirements.txt
  Brain Tumor Detectin using DL/Web App/styles/styles.css
  Brain Tumor Detectin using DL/Web App/styles/styles1.css
  Brain Tumor Detectin using DL/Web App/templates/error.html
  Brain Tumor Detectin using DL/Web App/templates/index.html
  Brain Tumor Detectin using DL/Web App/templates/result.html
  Brain Tumor Detectin using DL/requirements.txt
  Breast Cancer Detection/README.md
Labels: gssoc, level1

#271 Signature_verification_portal
  Signature_Verification_Portal/Dashboard.py
  Signature_Verification_Portal/README.md
  Signature_Verification_Portal/Validation.py
  Signature_Verification_Portal/__pycache__/Dashboard.cpython-310.pyc
  Signature_Verification_Portal/__pycache__/Validation.cpython-310.pyc
  Signature_Verification_Portal/app.py
  Signature_Verification_Portal/db.py
  Signature_Verification_Portal/example/01_049.png
  Signature_Verification_Portal/example/02_049.png
  Signature_Verification_Portal/mydatabase.db
  Signature_Verification_Portal/requirements.txt
  Signature_Verification_Portal/results/Annotation 2024-06-10 214407.png
  Signature_Verification_Portal/results/Annotation 2024-06-10 215239.png
  Signature_Verification_Portal/results/Capture.PNG
  Signature_Verification_Portal/user_credentials.csv
Labels: gssoc, level1

#277 Stress Prediction Project
  Stress Prediction/Human Stress Prediction/CountVectorizer.pkl
  Stress Prediction/Human Stress Prediction/Stress.csv
  Stress Prediction/Human Stress Prediction/Stress_Prediction.ipynb
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/__pycache__/info.cpython-38.pyc
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/__pycache__/settings.cpython-38.pyc
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/__pycache__/view.cpython-38.pyc
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/asgi.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/forms.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/info.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/model.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/settings.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/activation_failed.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/email_confirmation.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/home.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/index.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/signin.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/templates/signup.html
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/tokens.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/urls.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/view.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_Project/wsgi.py
  Stress Prediction/Human Stress Prediction/Stress_Prediction_model.pkl
  Stress Prediction/Human Stress Prediction/TfidfTransformer.pkl
  Stress Prediction/Human Stress Prediction/TfidifTransformer.pkl
  Stress Prediction/Human Stress Prediction/manage.py
  Stress Prediction/Human Stress Prediction/requirements.txt
Labels: gssoc, level1

#287 Create model.py
  Plant-Disease-Prediction/model.py
Labels: gssoc, level1

#286 Web-application for movie recommendation system
  Movie Recommendation system/.gitignore
  Movie Recommendation system/Procfile
  Movie Recommendation system/app.py
  Movie Recommendation system/main.py
  Movie Recommendation system/movie-recommender-system.ipynb
  Movie Recommendation system/movie_dict.pkl
  Movie Recommendation system/movies.pkl
  Movie Recommendation system/requirements.txt
  Movie Recommendation system/setup.sh
Labels: gssoc, level1

#281 Added AlexNet Model
  AlexNet.ipynb
Labels: gssoc, level1

#280 Create data_preprocessing.py
  Plant-Disease-Prediction/data_preprocessing.py
Labels: gssoc, level1

#279 Update README.md
  Plant-Disease-Prediction/README.md
Labels: gssoc, level1

#297 Original Pr made was not working on the leaderboard
  README.md
Labels: gssoc, level1

#295 Create train.py
  Plant-Disease-Prediction/train.py
Labels: gssoc, level1

#300 added Used car price prediction with Web Application
  used_car_price_prediction/.gitignore
  used_car_price_prediction/Procfile
  used_car_price_prediction/README.md
  used_car_price_prediction/application.py
  used_car_price_prediction/notebook/Quikr Analysis.ipynb
  used_car_price_prediction/notebook/data/Cleaned_Car_data.csv
  used_car_price_prediction/pickle_file/LinearRegressionModel.pkl
  used_car_price_prediction/requirements.txt
  used_car_price_prediction/static/css/style.css
  used_car_price_prediction/templates/index.html
Labels: gssoc, level1

#298 PR no - #283 Drowsiness Detection Using EEG Signals
  Drowsiness Detection using EEG signal/Drowsiness_detection_models.ipynb
  Drowsiness Detection using EEG signal/Images/Result.png
  Drowsiness Detection using EEG signal/Images/model_acc1.png
  Drowsiness Detection using EEG signal/Images/model_acc2.png
  Drowsiness Detection using EEG signal/Images/model_loss1.png
  Drowsiness Detection using EEG signal/Images/model_loss2.png
  Drowsiness Detection using EEG signal/README.md
Labels: gssoc, level1

#304 GSSOC level1 Liveliness detection
  liveliness detection/README.md
  liveliness detection/Requirements.txt
  liveliness detection/livelines_net.py
  liveliness detection/liveliness_detection.ipynb
  liveliness detection/project_antispoofing_model_97-0.969474.h5
  liveliness detection/project_antispoofing_model_mobilenet.json
Labels: gssoc, level1

#146 Image Classifier
  Image Classifier Using TensorFlow/ImageClassifierr.ipynb
  Image Classifier Using TensorFlow/README.md
  Image Classifier Using TensorFlow/happytest.jpg
  Image Classifier Using TensorFlow/sadtest.jpg
Labels: gssoc, level1

#315 Added new file with enhanced model for Facial Expression Recognition
  Facial_Expression_Recognition_with_PyTorch/Facial_Expression_Recognition_withEffNetb3_PyTorch.ipynb
Labels: gssoc, level1

#291 Hr prediction
  classification_task.ipynb
  hr-analysis/HR_Dataset.csv.xls
  hr-analysis/HR_dataset_analysis.ipynb
Labels: gssoc, level1

#290 [Feat]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level1

#207 Added : Data Cleaning Techniques
  Data Cleaning Techniques/1. Complete_case_analysis(Dropping rows).ipynb
  Data Cleaning Techniques/2. KNN-imputer.ipynb
  Data Cleaning Techniques/3. Adding_Missing_indicator_column.ipynb
  Data Cleaning Techniques/4. random_sample_imputation.ipynb
  Data Cleaning Techniques/5. Mean_median_missing_data.ipynb
  Data Cleaning Techniques/6. One_Hot_Encoding.ipynb
  Data Cleaning Techniques/7. Categorical_Feature_Ordinal_encoding.ipynb
  Data Cleaning Techniques/cars.csv
  Data Cleaning Techniques/customer.csv
  Data Cleaning Techniques/data_science_job.csv
  Data Cleaning Techniques/readme.md
  Data Cleaning Techniques/titanic_toy.csv
  Data Cleaning Techniques/train.csv
Labels: gssoc, level1

#132 Added prediction of Cardiovascular Disease
  Prediction-of-Cardiovascular-Disease-/Project Team-43.ipynb
  Prediction-of-Cardiovascular-Disease-/framingham (1).csv
Labels: gssoc, level1

#126 Pneumonia Detection from Chest X-Ray Images using Transfer Learning
  Colorization of Images/Code/Required Library & Package.txt
  Colorization of Images/Code/__init__.py
  Colorization of Images/Code/base_color.py
  Colorization of Images/Code/demo_release.py
  Colorization of Images/Code/eccv16.py
  Colorization of Images/Code/siggraph17.py
  Colorization of Images/Code/util.py
  Colorization of Images/Images/ILSVRC2012_val_00041580.JPEG
  Colorization of Images/Images/ILSVRC2012_val_00046524.JPEG
  Colorization of Images/Images/ILSVRC2012_val_00046834.JPEG
  Colorization of Images/Images/ansel_adams.jpg
  Colorization of Images/Images/ansel_adams2.jpg
  Colorization of Images/Images/ansel_adams3.jpg
  Colorization of Images/README.md
  Pneumonia Detection from Chest/Readme.md
  Pneumonia Detection from Chest/code/Detection of Pneumonia from Chest X-Ray Images 1.0.0.3.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images - Copy.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images 1.0.0.1.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images 1.0.0.2.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images Final.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images Modulerized 4.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images Modulerized.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images-Copy1.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images.ipynb
  Pneumonia Detection from Chest/code/obsolete/Detection of Pneumonia from Chest X-Ray Images2.ipynb
  Pneumonia Detection from Chest/code/obsolete/Short-Copy1.ipynb
  Pneumonia Detection from Chest/code/obsolete/Short.ipynb
  Pneumonia Detection from Chest/code/obsolete/Short2-Copy1.ipynb
  Pneumonia Detection from Chest/code/obsolete/Short_new.ipynb
  Pneumonia Detection from Chest/code/obsolete/finetuning_torchvision_models.ipynb
  Pneumonia Detection from Chest/code/obsolete/plot_precision_recall.ipynb
  Pneumonia Detection from Chest/code/obsolete/transfer_learning_tutorial.ipynb
  Pneumonia Detection from Chest/code/obsolete/util_helper.ipynb
  Pneumonia Detection from Chest/demo/images/result.png
  Pneumonia Detection from Chest/demo/obsolete/result.png
  Pneumonia Detection from Chest/demo/obsolete/sample.png
  Pneumonia Detection from Chest/demo/report/CM.png
  Pneumonia Detection from Chest/demo/sample/sample.png
Labels: gssoc, level1

#316 Added Feature-Engineering
  Feature-Engineering/Readme.md
Labels: gssoc, level1

#320 Explicit content classification
  Taylor-Swift-Classifier/Classification_of_explicit_content_of_Taylor_Swift.ipynb
  Taylor-Swift-Classifier/README.md
Labels: gssoc, level1

#335 Added NYC Taxi Trip Duration Prediction
  NYC Taxi Trip Duration Prediction/NYC_Taxi_Trip_Duration.ipynb
Labels: gssoc

#332 Feed-forward neural networks (Deep Learning Algorithm)
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/gender_submission.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/test.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/train.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/feedforwardnet.ipynb
  Feed-Forward Neural Networks (Deep Learning Algorithm)/requirments.txt
  Feed-Forward Neural Networks (Deep Learning Algorithm)/submission.csv
Labels: gssoc, level1

#322 Add Thyroid Cancer Recurrence Classification Model
  Thyroid Cancer Recurrence Classification/Dataset/README.md
  Thyroid Cancer Recurrence Classification/Dataset/Thyroid_Disease_Data.csv
  Thyroid Cancer Recurrence Classification/Dataset/final_test.csv
  Thyroid Cancer Recurrence Classification/Dataset/final_train.csv
  Thyroid Cancer Recurrence Classification/Images/Adenopathy_Distribution.png
  Thyroid Cancer Recurrence Classification/Images/Age_Distribution.png
  Thyroid Cancer Recurrence Classification/Images/Age_Distribution_by_Smoking_Status.png
  Thyroid Cancer Recurrence Classification/Images/Correlation_Matrix.png
  Thyroid Cancer Recurrence Classification/Images/Gender_Distribution.png
  Thyroid Cancer Recurrence Classification/Images/MLP_Model_Accuracy.png
  Thyroid Cancer Recurrence Classification/Images/MosaicPlot.png
  Thyroid Cancer Recurrence Classification/Images/Thyroid_Cancer_Recurrence_Dataset_EDA.png
  Thyroid Cancer Recurrence Classification/Model/Profile_Report.html
  Thyroid Cancer Recurrence Classification/Model/Thyroid_Cancer_Recurrence_Dataset_EDA.ipynb
  Thyroid Cancer Recurrence Classification/Model/Thyroid_Cancer_Recurrence_Prediction_w_DL.ipynb
  Thyroid Cancer Recurrence Classification/Model/autogluon_model.pkl
  Thyroid Cancer Recurrence Classification/Model/mlp_model.h5
  Thyroid Cancer Recurrence Classification/Model/tabnet_model.pt
  Thyroid Cancer Recurrence Classification/Model/tabnet_model_params.json
  Thyroid Cancer Recurrence Classification/README.md
  Thyroid Cancer Recurrence Classification/requirements.txt
Labels: gssoc, level1

#336 Rainfall_Prediction_using_ANN_and_Advanced_AI_model
  Rainfall prediction
  Rainfall_Prediction/ANN2.ipynb
  Rainfall_Prediction/Data_handling.ipynb
  Rainfall_Prediction/POWER_Point_Daily.csv
  Rainfall_Prediction/mnm
Labels: gssoc, level1

#339 Add "Multiple Additional Resources" for Machine Learning
  README.md
Labels: gssoc, level1

#337 Leaf
  leaf prediction/.gitignore
  leaf prediction/Main.ipynb
  leaf prediction/data.csv
  leaf prediction/readme.md
  leaf prediction/requirements.txt
Labels: gssoc, level1

#345 Update README.md
  Plant-Disease-Prediction/README.md
Labels: gssoc

#341 Spotify Track Popularity Prediction
  Spotify Track Popularity Prediction/README.md
  Spotify Track Popularity Prediction/Spotify_tack_popularity.ipynb
Labels: gssoc, level1

#333 Update README.md
  Drowsiness Detection using EEG signal/README.md
Labels: gssoc

#318 Added VGG16 model
  VGG16.ipynb
Labels: gssoc, level1

#355 Created PR template
  .github/pull_request_template.md
Labels: gssoc, level1

#354 Network Anomaly Detection using BiLSTM
  Network Anomaly Detection using BiLSTM/Network Anomaly Detection using BiLSTM.ipynb
Labels: gssoc, level1

#352 Pulmonary Disease Detection through Advanced Audio Analysis Project
  Pulmonary Infection Detection/Images/Accuracy.png
  Pulmonary Infection Detection/Images/CNN.png
  Pulmonary Infection Detection/Images/Counts of Diseases.png
  Pulmonary Infection Detection/Images/Diseases.png
  Pulmonary Infection Detection/Images/Heatmap.png
  Pulmonary Infection Detection/Images/Spectograms.png
  Pulmonary Infection Detection/README.md
  Pulmonary Infection Detection/main.py
  Pulmonary Infection Detection/requirements.txt
  Pulmonary Infection Detection/trained model.ipynb
Labels: gssoc, level1

#340 Convolutional neural networks (Deep Learning Algorithm) #137
  Convolutional neural networks (Deep Learning Algorithm)/ConvolutionNetworkStructure.ipynb
  Convolutional neural networks (Deep Learning Algorithm)/ConvolutoinBasic.ipynb
  Convolutional neural networks (Deep Learning Algorithm)/Dataset & Requirement.txt
  Convolutional neural networks (Deep Learning Algorithm)/FashionMnistCNN.ipynb
  Convolutional neural networks (Deep Learning Algorithm)/pictureUsedto-ConvolutionBasic/positive.jpg
Labels: gssoc, level1

#350 Gender Classification using Machine Learning
  Gender_Classification Using CNN/Gender_classification_ML.ipynb
  Gender_Classification Using CNN/README.md
  Gender_Classification Using CNN/main.py
  Gender_Classification Using CNN/output/aspect_ratio.png
  Gender_Classification Using CNN/output/epochs-loss_accuracy.png
  Gender_Classification Using CNN/output/image_result.png
  Gender_Classification Using CNN/output/image_result_female.png
  Gender_Classification Using CNN/output/web_app_interface.png
  Gender_Classification Using CNN/output/webcame_result.png
  Gender_Classification Using CNN/requirements.txt
  Gender_Classification Using CNN/static/styles.css
  Gender_Classification Using CNN/templates/index.html
  Gender_Classification Using CNN/templates/result.html
  Gender_Classification Using CNN/templates/upload.html
  Gender_Classification Using CNN/templates/webcam.html
Labels: gssoc, level1

#368 Added Multiple Projects In Machine Learning
  README.md
Labels: gssoc, level1

#367 Added "Additional books" for "machine learning"
  README.md
Labels: gssoc

#362 Updated README file
  README.md
Labels: gssoc

#370 Add Eye disease classification
  Eye Disease Classification/Dataset/README.md
  Eye Disease Classification/Images/CNN.png
  Eye Disease Classification/Images/Model summary.png
  Eye Disease Classification/Images/ResNet50.png
  Eye Disease Classification/Images/VGG16.png
  Eye Disease Classification/Model/Eye_Disease_classification.ipynb
  Eye Disease Classification/README.md
  Eye Disease Classification/Requirements.txt
Labels: gssoc, level1

#376 Added VGG19 Model
  VGG19.ipynb
Labels: gssoc, level1

#384 Asthma disease detection using Machine learning
  Asthma_Prediction_ML/Asthma_detection_ML.ipynb
  Asthma_Prediction_ML/asthma_detection.csv
  Asthma_Prediction_ML/main.py
  Asthma_Prediction_ML/output/box_plot.png
  Asthma_Prediction_ML/output/confusion_matrix-random_forest.png
  Asthma_Prediction_ML/output/confusion_matrix-svm.png
  Asthma_Prediction_ML/output/correlation_matrix_heatmap.png
  Asthma_Prediction_ML/output/count_plot.png
  Asthma_Prediction_ML/output/histogram.png
  Asthma_Prediction_ML/output/output-1.png
  Asthma_Prediction_ML/output/output-2.png
  Asthma_Prediction_ML/output/pie-chart.png
  Asthma_Prediction_ML/output/rf_svm_comparison.png
  Asthma_Prediction_ML/output/violen-plot.png
  Asthma_Prediction_ML/readme.md
  Asthma_Prediction_ML/requirements.txt
  Asthma_Prediction_ML/rf_asthma_model_prediction.pkl
Labels: gssoc, level1

#372 PR no. #366 -->💡[Feature]: Sarcasm Detection Model using Machine Learning(NLP)
  Sarcasm Detection using NLP/Dataset/dataset
  Sarcasm Detection using NLP/Images/model1_acc.png
  Sarcasm Detection using NLP/Images/model1_loss.png
  Sarcasm Detection using NLP/Images/model7_acc.png
  Sarcasm Detection using NLP/Images/model7_loss.png
  Sarcasm Detection using NLP/Model/Sarcasm_detection_NLP.ipynb
  Sarcasm Detection using NLP/README.md
  Sarcasm Detection using NLP/requirements.txt
Labels: gssoc, level1

#385 Outlier Detection Techniques
  Outlier Detection Techniques/IQR.ipynb
  Outlier Detection Techniques/bhp.csv
  Outlier Detection Techniques/percentile.ipynb
  Outlier Detection Techniques/readme.md
  Outlier Detection Techniques/weight-height.csv
  Outlier Detection Techniques/zscore.ipynb
Labels: gssoc, level1

#390 Added the Restaurant Recommender
  Restaurant Recommender/Restaurant_Reservation.ipynb
  Restaurant Recommender/food1.csv
  Restaurant Recommender/main_rest.csv
Labels: gssoc, level1

#323 Traffic Management
  Traffic Management/Demo_video.mp4
  Traffic Management/INSTRUCTIONS.pdf
  Traffic Management/__pycache__/vehicle_detector.cpython-311.pyc
  Traffic Management/__pycache__/vehicle_detector.cpython-312.pyc
  Traffic Management/image/1.jpg
  Traffic Management/image/3.jpg
  Traffic Management/image/4.jpg
  Traffic Management/image/5.jpg
  Traffic Management/image_repeat/5.jpg
  Traffic Management/image_repeat/6.jpg
  Traffic Management/image_repeat/7.jpg
  Traffic Management/image_repeat/8.jpg
  Traffic Management/images/1.jpg
  Traffic Management/images/10.jpg
  Traffic Management/images/2.jpg
  Traffic Management/images/3.jpg
  Traffic Management/images/4.jpg
  Traffic Management/images/5.jpg
  Traffic Management/images/6.jpg
  Traffic Management/images/7.jpg
  Traffic Management/images/8.jpg
  Traffic Management/images/down/bike.png
  Traffic Management/images/down/bus.png
  Traffic Management/images/down/car.png
  Traffic Management/images/down/truck.png
  Traffic Management/images/intersection.png
  Traffic Management/images/left/bike.png
  Traffic Management/images/left/bus.png
  Traffic Management/images/left/car.png
  Traffic Management/images/left/truck.png
  Traffic Management/images/right/bike.png
  Traffic Management/images/right/bus.png
  Traffic Management/images/right/car.png
  Traffic Management/images/right/truck.png
  Traffic Management/images/signals/green.png
  Traffic Management/images/signals/red.png
  Traffic Management/images/signals/yellow.png
  Traffic Management/images/up/bike.png
  Traffic Management/images/up/bus.png
  Traffic Management/images/up/car.png
  Traffic Management/images/up/truck.png
  Traffic Management/simulation.py
  Traffic Management/vehicle_counting.py
  Traffic Management/vehicle_detector.py
  mnist dataset/.ipynb_checkpoints/MNIST dataset -checkpoint.ipynb
  mnist dataset/MNIST dataset .ipynb
  traffic mang.zip
Labels: gssoc, level1

#393 Predict of h1n1 and seasonal flu vaccine
  Flu-Feature_Selection.ipynb
  Flu_CatBoost-tuned-OptunaCVI.ipynb
  Flu_analysis-manual.ipynb
  Flu_analysis-pandas.ipynb
Labels: gssoc, level1

#421 Cricket player analysis
  Cricket player analysis/Cricket player analysis.ipynb
  Cricket player analysis/Cricket.csv
  Cricket player analysis/README.md
Labels: gssoc, level1

#420 Closes #392 Advanced ARIMA Time Series Forecast
  Seasonal_Time_Series/Seasonal_Time_Series.ipynb
  Seasonal_Time_Series/perrin-freres-monthly-champagne-.csv
  Seasonal_Time_Series/readme.md
Labels: help wanted, gssoc, level1

#409 Stock Turnover Ratio Dataset Analysis
  Stock Turnover Ratio Dataset Analysis/DDEM01USA156NWDB.csv
  Stock Turnover Ratio Dataset Analysis/StockTurnoverRatio.ipynb
  Stock Turnover Ratio Dataset Analysis/requirement.txt
Labels: gssoc, level1

#413 Added Real Estate Price Predictions
  Real Estate Price Predictions/Real_estate_predictions.ipynb
  Real Estate Price Predictions/bengaluru_house_prices.csv
Labels: gssoc, level1

#417 compressed file for mnist dataset
  mnist dataset/.ipynb_checkpoints/MNIST dataset -checkpoint.ipynb
Labels: gssoc, level1

#426 Created using Colab
  FashionClassification.ipynb
Labels: gssoc, level1

#424 Basic workflow for model creation.
  WorkFlow for Basic Model Creation/README.md
  WorkFlow for Basic Model Creation/load_digits_Scikit_learn.ipynb
  WorkFlow for Basic Model Creation/load_digits_TensorFlow.h5
  WorkFlow for Basic Model Creation/load_digits_Tensorflow.ipynb
  WorkFlow for Basic Model Creation/load_digits_dataset
Labels: gssoc, level1

#423 Istanbul Stock Exchange
  Istanbul Stock Exchange/IstanbulStockExchange.ipynb
  Istanbul Stock Exchange/istanbul_stock_exchange.csv
  Istanbul Stock Exchange/requirement.txt
  Uniqlo Stock Price Dataset Analysis/Dataset/Uniqlo(FastRetailing) 2012-2016 Training - stocks2012-2016.csv
  Uniqlo Stock Price Dataset Analysis/Dataset/Uniqlo(FastRetailing) 2017 Test - stocks2017.csv
  Uniqlo Stock Price Dataset Analysis/UniqloStock.ipynb
  Uniqlo Stock Price Dataset Analysis/requirement.txt
  Uniqlo Stock Price Dataset Analysis/uniqlo_stock_prediction_model.h5
Labels: gssoc, level1

#446 Added Multiple Additional "Resources" for "Machine Learning"
  README.md
Labels: gssoc

#430 Created using Colab
  Matplotlib_Beginner.ipynb
Labels: gssoc, level1

#462 Adding Air quality analysis and Health Impact score prediction and th…
  Air quality analysis and Health Impact score prediction/Air quality analysis and Health Impact score prediction.ipynb
  Air quality analysis and Health Impact score prediction/air_quality_health_impact_data.csv
Labels: gssoc, level1

#461 Added python code for neural network building from scratch
  Neural Network from scratch/Nueral_Network.ipynb
Labels: gssoc, level1

#458 Customer Purchase Behaviour Prediction
  Customer Purchase Behaviour Prediction/Readme.md
  Customer Purchase Behaviour Prediction/customer_purchase_behaviour_prediction.ipynb
Labels: gssoc, level1

#453 Added Landscape detection Folder
  Landscape Change Detection/Deforestation.ipynb
  Landscape Change Detection/README.MD
  Landscape Change Detection/building.ipynb
Labels: gssoc, level1

#451 added the fruit classification model
  Fruit Classification Model/README.md
  Fruit Classification Model/fruit-image-classification.ipynb
Labels: gssoc, level1

#476 linear regression for house price prediction
  .DS_Store
  house-price-prediction/Price_of_houses_prediction-2.ipynb
  house-price-prediction/price_of_houses_prediction.py
  house-price-prediction/test.csv
  house-price-prediction/train.csv
Labels: gssoc, level1

#468 added garbage classification model
  Garbage Classification Model/README.md
  Garbage Classification Model/garbage-classification.ipynb
Labels: gssoc, level1

#474 Chi-Square Test
  Chi-Square Test/ChiSquareTestDocumentation.docx
  Chi-Square Test/Chi_Square_Test.ipynb
  Chi-Square Test/dataset.csv
  Chi-Square Test/requirement.txt
Labels: gssoc, level1

#469 Adding earthquake prediction model
  Earthquake_prediction/earthquake_prediction.ipynb
Labels: gssoc, level1

#482 Kruskal-Wallis Test
  Kruskal-Wallis Test/kruskal_wallis_data (1).csv
  Kruskal-Wallis Test/kruskalwallis.ipynb
  Kruskal-Wallis Test/requirement.txt
Labels: gssoc, level1

#481 Wilcoxon Signed-Rank Test
  Wilcoxon Signed-Rank Test/WilcoxonSigned-RankTest.ipynb
  Wilcoxon Signed-Rank Test/paired_data (2).csv
  Wilcoxon Signed-Rank Test/requirement.txt
Labels: gssoc, level1

#414 Added ResNet50 Model
  ResNet50/ResNet50.ipynb
Labels: gssoc, level1

#485 CDS using Random Forest
  Predict CDS using Random Forest/Predict CDS using Random Forest.ipynb
Labels: gssoc, level1

#495 Word Embedding System Using Pytorch
  Word Embedding System in Pytorch/README.md
  Word Embedding System in Pytorch/WordEmbedding.py
Labels: gssoc, level1

#492 Added QR code Scanner
  QR-Scanner/qr_scan.py
Labels: gssoc, level1

#443 Added autism-identification
  Autism Identification/autism_identification_notebook.ipynb
Labels: gssoc, level1

#499 Added Fake Job Description Prediction
  Fake Job Description Prediction/Fake Job Description Prediction.ipynb
Labels: gssoc, level1

#498 Added Domestic Violence Against Women Classification
  Domestic Violence Against Women Classification/Dataset/readme.md
  Domestic Violence Against Women Classification/domestic_violence_against_women_classification.ipynb
  Domestic Violence Against Women Classification/readme.md
Labels: gssoc, level1

#480 Mann-Whitney U Test
  Mann-Whitney U Test/Mann-WhitneyUTest.ipynb
  Mann-Whitney U Test/Requirement.txt
  Mann-Whitney U Test/mann_whitney_sample_data (1).csv
Labels: gssoc, level1

#488 Hypothesis Testing Techniques
  Hypothesis Testing Techniques/HypothesisTesting.ipynb
  Hypothesis Testing Techniques/Hypothesis_Testing_Techniques_Project.docx
  Hypothesis Testing Techniques/requirement.txt
  Hypothesis Testing Techniques/teaching_methods_test_scores.csv
Labels: gssoc, level1
