Repository recodehive/machine-learning-repos, pull requests merged in 2024-08, with the labels that each got.

#1075 Adding the machine learning model to predict the efficiency of smart …
  Smart Home Device Efficiency/Smart Home Device Efficiency.ipynb
  Smart Home Device Efficiency/smart_home_device_usage_data.csv
Labels: gssoc, level3

#1073 Advanced House price prediction
  Advanced House Price Predictions/main.ipynb
Labels: gssoc, level1

#1080 Added Migration Prediction
  Migration_Prediction/Dataset/migration_nz.csv
  Migration_Prediction/Images/image1.png
  Migration_Prediction/Images/image2.png
  Migration_Prediction/Images/image3.png
  Migration_Prediction/Model/Migration_Prediction.ipynb
Labels: gssoc, level2

#1060 interest-rate-prediction added
  interest-rate-prediction/interest-rate-prediction.ipynb
Labels: gssoc, level3

#1057 Postman Challenge PR merged, but Points not added
  CONTRIBUTING.md
Labels: gssoc, level3

#1045 Box office revenue prediction added
  Boxoffice/Boxoffice.ipynb
Labels: gssoc, level2

#1030 add pet facial expression detection
  Pet's Facial Expression/Dataset/README.md
  Pet's Facial Expression/Images/ConfusionMatrix_ViT.png
  Pet's Facial Expression/Images/Dataset.png
  Pet's Facial Expression/Images/EfficientNet_plot.png
  Pet's Facial Expression/Images/ResNet50_Plot.png
  Pet's Facial Expression/Models/README.md
  Pet's Facial Expression/Models/pet-s-facial-expression-detection-resnet-50.ipynb
  Pet's Facial Expression/Models/pets-facial-expression-efficientnet.ipynb
  Pet's Facial Expression/Models/pets-facial-expression-vit.ipynb
  Pet's Facial Expression/README.md
Labels: gssoc, level3

#992 #877 Startup Analysis
  Startups Analysis/Dataset/dataset.csv
  Startups Analysis/Images/Industries vs cities.png
  Startups Analysis/Images/countries vs industries.png
  Startups Analysis/Images/industries count in india.png
  Startups Analysis/Images/missing_values.png
  Startups Analysis/Images/no_of_observation_by_industry.png
  Startups Analysis/Images/no_of_observations_by_country.png
  Startups Analysis/Images/valuation of companies by industry.png
  Startups Analysis/Images/year vs startups.png
  Startups Analysis/Model/README.md
  Startups Analysis/Model/Startups_Analysis.ipynb
Labels: gssoc, level2

#1083 Added Bone Marrow Classification Model
  Bone Marrow Classification/README.md
  Bone Marrow Classification/dataset/README.md
  Bone Marrow Classification/images/DenseNet.png
  Bone Marrow Classification/images/EDA.png
  Bone Marrow Classification/images/VGG16.png
  Bone Marrow Classification/images/efficient net b5.png
  Bone Marrow Classification/images/mobileNet.png
  Bone Marrow Classification/model/model.ipynb
  Bone Marrow Classification/requirements.txt
Labels: gssoc, level3

#1092 automate-text-classification
  Automate Documents Categorization- PyTorch & Neural Networks/Text Classification.ipynb
Labels: gssoc, level3

#1100 WCE Curated Colon Disease Detection
  WCE Curated Colon Disease Detection/README.md
  WCE Curated Colon Disease Detection/WCE_Curated_Colon_Disease_Detection.ipynb
  WCE Curated Colon Disease Detection/requirements.txt
Labels: gssoc, level3

#1102 Text Summarization Model using Langchain and LLAMA2
  Text_Summarization_Model_Langchain_LLAMA2/README.md
  Text_Summarization_Model_Langchain_LLAMA2/langchain_llama2.ipynb
Labels: gssoc, level3

#1103 Update README.md
  README.md
Labels: gssoc, level2

#1109 Quality Prediction in Mining Process
  Quality Prediction in Mining Process/Dataset/README.md
  Quality Prediction in Mining Process/Images/eda 1.jpg
  Quality Prediction in Mining Process/Images/eda 2.jpg
  Quality Prediction in Mining Process/Images/iron mine.jpg
  Quality Prediction in Mining Process/Model/quality-prediction-mining.ipynb
  Quality Prediction in Mining Process/README.md
  Quality Prediction in Mining Process/requirements.txt
Labels: gssoc, level2

#1113 Automatic_Web_Scrapper and nlp analysis
  Automatic_web_Scrapper.ipynb
  Input.xlsx
  output.csv
Labels: gssoc, level3

#1120 added LM using n-gram
  Language model Using N-Gram/n_gram_model.ipynb
  Language model Using N-Gram/readme.md
Labels: gssoc, level3

#1119 DROWSINESS DETECTION
  Drowsiness detection/README.md
  Drowsiness detection/Untitled.ipynb
Labels: gssoc, level3

#1117 Ocr fine tuning
  Image_segmenattion_finetuning.py
  image_preprocessing_ocrfinetuning.py
Labels: gssoc, level3

#1125 Adds Depth Estimation with DepthAnything and OpenVINO
  Depth estimation with DepthAnything and OpenVINO/README.md
  Depth estimation with DepthAnything and OpenVINO/depth-anything-v2.ipynb
  Depth estimation with DepthAnything and OpenVINO/depth-anything.ipynb
Labels: gssoc, level2

#1121 added hand detection using openCv
  Hand detection package/Hand_detection_module.py
  Hand detection package/Raw code module.py
  Hand detection package/__pycache__/Hand_detection_module.cpython-38.pyc
  Hand detection package/readme.md
Labels: gssoc, level3
